// Pokemon Ranger: Shadows of Almia
// #ID = 16296
// RA Hash: 26ca96f719ec88e9ea90191e386df889
// $0B0218: [NBit] DLC Mission Bitflags
//          0x00 = NEW
//          0x01= CLEAR
//          Bit0= Recover the Manaphy Egg!
//          Bit1=Rescue Kidnapped Riolu!
//          Bit2=Liberate the Tower!
// $0B32CD: [NBit] Quest Menu Flags: Calm Down Miltank
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32CE: [NBit] Quest Menu Flags: Breeze Hill Sign Recovery
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32CF: [NBit] Quest Menu Flags: Is Combee Okay?
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D0: [NBit] Quest Menu Flags: Clear the Crates!
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D1: [NBit] Quest Menu Flags: The Boy Who Cried Lumineon
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D2: [NBit] Quest Menu Flags: Nosepass! Must Have Nosepass!
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D3: [NBit] Quest Menu Flags: Who Ate My Lunch!?
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D4: [NBit] Quest Menu Flags: Eevee for Marital Bliss
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D5: [NBit] Quest Menu Flags: Oddish Research
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D6: [NBit] Quest Menu Flags: Light the Leaves
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D7: [NBit] Quest Menu Flags: Clear Some Fallen Logs
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D8: [NBit] Quest Menu Flags: Cherrim, Cherrim, Come to Us
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32D9: [NBit] Quest Flags: Team Dim Sun's Appetite
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32DA: [NBit] Quest Menu Flags: That Smell of Muk...
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32DB: [NBit] Quest Menu Flags: Dim... Sun... Come Back...
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32DC: [NBit] Quest Menu Flags: Apologies to Vespiquen
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32DD: [NBit] Quest Menu Flag: Lonely Chingling
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32DE: [NBit] Quest Menu Flags: Abomasnow Research
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32DF: [NBit] Quest Menu Flags: Melt the Ice!
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E0: [NBit] Quest Menu Flags: Difblim's Moving Service
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E1: [NBit] Quest Menu Flags: Secure the Hidden Harbor
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E2: [NBit] Quest Menu Flags: Thaw the Frozen Door
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E3: [NBit] Quest Menu Flags: My Precious Fishing Rod
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E4: [NBit] Quest Menu Flags: Unidentified Fleeing Omaster
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E5: [NBit] Quest Menu Flags: Cacturne Research
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E6: [NBit] Quest Menu Flags: Smell of Skuntank and Weezing
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E7: [NBit] Quest Menu Flags: Capture Gigaremo Units
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E8: [NBit] Quest Menu Flags: Elaine's Favorite
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32E9: [NBit] Quest Menu Flags: Murph's Ranger Contest
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32EA: [NBit] Quest Menu Flags: Roserade Red, Roserade Blue?
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32EB: [NBit] Quest Menu Flags: Charge Up the Trio!
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32EC: [NBit] Quest Menu Flags: Access the Ice Castle
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32ED: [NBit] Quest Menu Flags: Mom's Recipe
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32EE: [NBit] Quest Flags: White Pokemon for Peace?
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32EF: [NBit] Quest Menu Flags: Please Save Cranidos
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F0: [NBit] Quest Flags: Please Save Shieldon
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F1: [NBit] Quest Menu Flags: Please Save Chimchar
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F2: [NBit] Quest Flags: Mischievous Sneasel
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F3: [NBit] Quest Flags: Snover's Mysterious Presence
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F4: [NBit] Quest Menu Falgs: Misdreavus Mischief Mystery!
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F5: [NBit] Quest Menu Flags: Pachirisu's Hide & Seek
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F6: [NBit] Quest Menu Flags: Things That Go Bump...
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F7: [NBit] Quest Menu Flags: Starly Lost Its Way
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F8: [NBit] Quest Menu Flags: What Happened to Machop!?
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32F9: [NBit] Quest Menu Flags: Please Save Piplup
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32FA: [NBit] Quest Menu Flags: Please Save Turtwig
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32FB: [NBit] Quest Menu Flags: Who Is on Hippowdon's Nose?
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32FC: [NBit] Quest Menu Flags: Pelipper's Plea
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32FD: [NBit] Quest Menu Flags: Under the Bridge
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32FE: [NBit] Quest Menu Flags: Strange Crates Washed Ashore
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B32FF: [NBit] Quest Menu Flags: Go Talk to My Mom
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3300: [NBit] Quest Menu Flags: What Reporter Hans Forgot
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3301: [NBit] Quest Menu Flags: Bring Back the Oasis!
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3302: [NBit] Quest Menu Flags: Wish for the Vien Forest
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3303: [NBit] Quest Menu Flags: Secret Kept by Three
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3304: [NBit] Quest Menu Flags: Snow in Boyleland
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3305: [NBit] Quest Menu Flags: For Little Tim
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3306: [NBit] Quest Menu Flags: Murph's Disappearing Act
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3307: [NBit] Quest Menu Flags: Staraptor High in the Sky
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3308: [NBit] Quest Menu Flags: Gift of Music for Isaac
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3309: [NBit] Quest Menu Flags: Ponte's Path to Take
//          Bit0=Available
//          Bit1=Mission Cleared
//          Bit4=Name Visible
// $0B3320: [8bit] Character Gender
//          0x00=Male
//          0x01=Female
// $0B3321: Health Amount (Main GUI)
function environment_health() => byte(0x0b3321)
// $0B3322: Max Amount of Health (Main GUI)
// $0B333A: [8bit] Room ID
function location() => word(0x0b333a)
// $0B3348: Styler Current exp [32bit]
// $0B334C: [32bit] Player Exp Total (Shows on Ranger Record)
// $0BAF5D: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Charmander
//          Bit2-3=Charmeleon
//          Bit4-5=Charizard
//          Bit6-7=Squirtle
// $0BAF5E: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Wartortle
//          Bit2-3=Blastoise
// $0BAF5F: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit2-3=Weedle
//          Bit6-7=Beedrill
// $0BAF60: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit6-7=Rattata
// $0BAF61: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Raticate
//          Bit2-3=Spearow
//          Bit4-5=Fearow
// $0BAF62: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Null
//          Bit2-3=Pikachu
//          Bit4-5=Raichu
//          Bit6-7=Sandshrew
// $0BAF63: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Sandslash
// $0BAF65: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit2-3=Vulpix
//          Bit4-5=Ninetales
//          Bit6-7=Jigglypuff
// $0BAF66: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Wigglytuff
//          Bit2-3=Zubat
//          Bit4-5=Golbat
//          Bit6-7=Oddish
// $0BAF67: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Gloom
//          Bit2-3=Vileplume
// $0BAF6A: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Mankey
//          Bit2-3=Primeape
//          Bit4-5=Growlithe
//          Bit6-7=Arcanine
// $0BAF6B: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit6-7=Abra
// $0BAF6C: [NBit] Pokemon Bitflags
//          Bit2-3 =Alakazam
//          Bit4-5 =Machop
//          Bit6-7 =Machoke
// $0BAF6D: [NBit] Pokemon Bitflags
//          Bit0-1=Machamp
//          Bit6-7 =Victreebel
// $0BAF6E: [NBit] Pokemon Bitflags
//          Bit2-3 =Tentacruel
//          Bit4-5 =Geodude
//          Bit6-7 =Graveler
// $0BAF6F: [NBit] Pokemon Bitflags
//          Bit0-1=Golem
//          Bit2-3 =Ponyta
//          Bit4-5 =Rapidash
// $0BAF70: [NBit] Pokemon Bitflags
//          Bit2-3 =Magnemite
//          Bit4-5 =Magneton
// $0BAF71: [NBit] Pokemon Bitflags
//          Bit0-1=Doduo
//          Bit2-3 =Dodrio
// $0BAF72: [NBit] Pokemon Bitflags
//          Bit2-3=Muk
// $0BAF73: [NBit] Pokemon Bitflags
//          Bit0-1=Gastly
//          Bit2-3 =Haunter
//          Bit4-5 =Gengar
// $0BAF74: [NBit] Pokemon Bitflags
//          Bit0-1=Drowzee
//          Bit2-3 =Hypno
// $0BAF75: [NBit] Pokemon Bitflags
//          Bit0-1=Voltorb
//          Bit2-3 =Electrode
// $0BAF77: [NBit] Pokemon Bitflags
//          Bit2-3 =Koffing
//          Bit4-5 =Weezing
//          Bit6-7 =Rhyhorn
// $0BAF78: [NBit] Pokemon Bitflags
//          Bit0-1=Rhydon
//          Bit6-7 =Kangaskhan
// $0BAF79: [NBit] Pokemon Bitflags
//          Bit0-1=Horsea
//          Bit2-3 =Seadra
// $0BAF7A: [NBit] Pokemon Bitflags
//          Bit0-1=Staryu
//          Bit2-3 =Starmie
//          Bit4-5 =Mr. Mime
//          Bit6-7 =Scyther
// $0BAF7B: [NBit] Pokemon Bitflags
//          Bit0-1=Jynx
//          Bit2-3 =Electabuzz
//          Bit4-5 =Magmar
//          Bit6-7 =Pinsir
// $0BAF7C: [NBit] Pokemon Bitflags
//          Bit0-1=Tauros
// $0BAF7D: [NBit] Pokemon Bitflags
//          Bit2-3 =Eevee
//          Bit4-5 =Vaporeon
//          Bit6-7 =Jolteon
// $0BAF7E: [NBit] Pokemon Bitflags
//          Bit0-1=Flareon
//          Bit4-5 =Omanyte
//          Bit6-7 =Omastar
// $0BAF7F: [NBit] Pokemon Bitflags
//          Bit4-5 =Aerodactyl
// $0BAF80: [NBit] Pokemon Bitflags
//          Bit6-7 =Dratini
// $0BAF81: [NBit] Pokemon Bitflags
//          Bit0-1=Dragonair
// $0BAF85: [NBit] Pokemon Bitflags
//          Bit6-7 =Spinarak
// $0BAF86: [NBit] Pokemon Bitflags
//          Bit0-1=Ariados
//          Bit2-3 =Crobat
//          Bit4-5 =Chinchou
//          Bit6-7 =Lanturn
// $0BAF87: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Pichu
// $0BAF88: [NBit] Pokemon Bitflags
//          Bit6-7 =Mareep
// $0BAF89: [NBit] Pokemon Bitflags
//          Bit0-1=Flaaffy
//          Bit2-3 =Ampharos
//          Bit4-5 =Bellossom
// $0BAF8A: [NBit] Pokemon Bitflags
//          Bit2-3 =Sudowoodo
// $0BAF8B: [NBit] Pokemon Bitflags
//          Bit4-5 =Aipom
// $0BAF8C: [NBit] Pokemon Bitflags
//          Bit2-3 =Yanma
// $0BAF8D: [NBit] Pokemon Bitflags
//          Bit0-1=Espeon
//          Bit2-3 =Umbreon
//          Bit4-5 =Murkrow
// $0BAF8E: [NBit] Pokemon Bitflags
//          Bit0-1=Misdreavus
//          Bit6-7 =Girafarig
// $0BAF8F: [NBit] Pokemon Bitflags
//          Bit0-1=Pineco
//          Bit2-3 =Forretress
//          Bit6-7 =Gligar
// $0BAF90: [NBit] Pokemon Bitflags
//          Bit6-7 =Qwilfish
// $0BAF91: [NBit] Pokemon Bitflags
//          Bit0-1=Scizor
//          Bit6-7 =Sneasel
// $0BAF92: [NBit] Pokemon Bitflags
//          Bit4-5 =Slugma
//          Bit6-7 =Magcargo
// $0BAF93: [NBit] Pokemon Bitflags
//          Bit0-1=Swinub
//          Bit2-3 =Piloswine
//          Bit4-5 =Corsola
// $0BAF94: [NBit] Pokemon Bitflags
//          Bit2-3 =Delibird
//          Bit4-5 =Mantine
//          Bit6-7 =Skarmory
// $0BAF95: [NBit] Pokemon Bitflags
//          Bit0-1=Houndour
//          Bit2-3 =Houndoom
//          Bit4-5 =Kingdra
// $0BAF97: [NBit] Pokemon Bitflags
//          Bit0-1=Tyrogue
//          Bit6-7 =Elekid
// $0BAF98: [NBit] Pokemon Bitflags
//          Bit0-1=Magby
//          Bit2-3 =Miltank
// $0BAF99: [NBit] Pokemon Bitflags
//          Bit4-5 =Larvitar
//          Bit6-7 =Pupitar
// $0BAF9A: [NBit] Pokemon Bitflags
//          Bit0-1=Tyranitar
//          Bit6-7 =Celebi
// $0BAF9B: [NBit] Pokemon Bitflags
//          Bit4-5 =Sceptile
// $0BAF9C: [NBit] Pokemon Bitflags
//          Bit2-3 =Blaziken
// $0BAFA0: [NBit] Pokemon Bitflags
//          Bit2-3 =Seedot
//          Bit4-5 =Nuzleaf
//          Bit6-7 =Shiftry
// $0BAFA1: [NBit] Pokemon Bitflags
//          Bit0-1=Tailow
//          Bit2-3 =Swellow
//          Bit4-5 =Wingull
//          Bit6-7 =Pelipper
// $0BAFA2: [NBit] Pokemon Bitflags
//          Bit0-1=Ralts
//          Bit2-3 =Kirlia
//          Bit4-5 =Gardevoir
// $0BAFA3: [NBit] Pokemon Bitflags
//          Bit6-7 =Slakoth
// $0BAFA4: [NBit] Pokemon Bitflags
//          Bit6-7 =Ninjask
// $0BAFA6: [NBit] Pokemon Bitflags
//          Bit0-1=Makuhita
//          Bit2-3 =Hariyama
//          Bit6-7 =Nosepass
// $0BAFA7: [NBit] Pokemon Bitflags
//          Bit4-5 =Sableye
//          Bit6-7 =Mawile
// $0BAFA8: [NBit] Pokemon Bitflags
//          Bit0-1=Aron
//          Bit2-3 =Lairon
//          Bit4-5 =Aggron
// $0BAFAA: [NBit] Pokemon Bitflags
//          Bit6-7 =Roselia
// $0BAFAB: [NBit] Pokemon Bitflags
//          Bit6-7 =Sharpedo
// $0BAFAC: [NBit] Pokemon Bitflags
//          Bit0-1=Wailmer
//          Bit2-3 =Wailord
//          Bit4-5 =Numel
//          Bit6-7 =Camerupt
// $0BAFAD: [NBit] Pokemon Bitflags
//          Bit0-1=Torkoal
// $0BAFAE: [NBit] Pokemon Bitflags
//          Bit4-5 =Flygon
//          Bit6-7 =Cacnea
// $0BAFAF: [NBit] Pokemon Bitflags
//          Bit0-1=Cacturne
//          Bit4-5 =Altaria
// $0BAFB2: [NBit] Pokemon Bitflags
//          Bit0-1=Claydol
// $0BAFB4: [NBit] Pokemon Bitflags
//          Bit2-3 =Shuppet
//          Bit4-5 =Banette
//          Bit6-7 =Duskull
// $0BAFB5: [NBit] Pokemon Bitflags
//          Bit0-1=Dusclops
//          Bit6-7 =Absol
// $0BAFB6: [NBit] Pokemon Bitflags
//          Bit2-3 =Snorunt
//          Bit4-5 =Glalie
//          Bit6-7 =Spheal
// $0BAFB7: [NBit] Pokemon Bitflags
//          Bit0-1=Sealeo
//          Bit2-3 =Walrein
//          Bit6-7 =Huntail
// $0BAFB8: [NBit] Pokemon Bitflags
//          Bit0-1=Gorebyss
//          Bit6-7 =Bagon
// $0BAFB9: [NBit] Pokemon Bitflags
//          Bit0-1=Shelgon
//          Bit2-3 =Salamence
// $0BAFBA: [NBit] Pokemon Bitflags
//          Bit2-3 =Regirock
//          Bit4-5 =Regice
//          Bit6-7 =Registeel
// $0BAFBC: [NBit] Pokemon Bitflags
//          Bit6-7 =Turtwig
// $0BAFBD: [NBit] Pokemon Bitflags
//          Bit0-1=Grotle
//          Bit2-3 =Torterra
//          Bit4-5 =Chimchar
//          Bit6-7 =Monferno
// $0BAFBE: [NBit] Pokemon Bitflags
//          Bit0-1=Infernape
//          Bit2-3 =Piplup
//          Bit4-5 =Prinplup
//          Bit6-7 =Empoleon
// $0BAFBF: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Starly
//          Bit2-3=Staravia
//          Bit4-5=Staraptor
//          Bit6-7=Bidoof
// $0BAFC0: [NBit] Pokemon Bitflags
//          First Bit of Pokemon = Seen
//          Second Bit of Pokemon = Befriended
//          First Bit flips to Zero when pokemon is befriended:
//          Bit0-1=Bibarel
//          Bit2-3=Kricketot
//          Bit4-5=Kricketune
//          Bit6-7=Shinx
// $0BAFC1: [NBit] Pokemon Bitflags
//          Bit0-1=Luxio
//          Bit2-3 =Luxray
//          Bit4-5 =Budew
//          Bit6-7 =Roserade
// $0BAFC2: [NBit] Pokemon Bitflags
//          Bit0-1=Cranidos
//          Bit2-3 =Rampardos
//          Bit4-5 =Shieldon
//          Bit6-7 =Bastiodon
// $0BAFC3: [NBit] Pokemon Bitflags
//          Bit4-5 =Mothim
//          Bit6-7 =Combee
// $0BAFC4: [NBit] Pokemon Bitflags
//          Bit0-1=Vespiquen
//          Bit2-3 =Pachirisu
//          Bit4-5 =Buizel
//          Bit6-7 =Floatzel
// $0BAFC5: [NBit] Pokemon Bitflags
//          Bit0-1=Cherubi
//          Bit2-3 =Cherrim
//          Bit4-5 =Shellos
//          Bit6-7 =Gastrodon
// $0BAFC6: [NBit] Pokemon Bitflags
//          Bit0-1=Ambipom
//          Bit2-3 =Drifloon
//          Bit4-5 =Drifblim
//          Bit6-7 =Buneary
// $0BAFC7: [NBit] Pokemon Bitflags
//          Bit0-1=Lopunny
//          Bit2-3 =Mismagius
//          Bit4-5 =Honchkrow
//          Bit6-7 =Glameow
// $0BAFC8: [NBit] Pokemon Bitflags
//          Bit0-1=Purugly
//          Bit2-3 =Chingling
//          Bit4-5 =Stunky
//          Bit6-7 =Skuntank
// $0BAFC9: [NBit] Pokemon Bitflags
//          Bit0-1=Bronzor
//          Bit2-3 =Bronzong
//          Bit4-5 =Bonsly
//          Bit6-7 =Mime Jr.
// $0BAFCA: [NBit] Pokemon Bitflags
//          Bit0-1=Happiny
//          Bit2-3 =Chatot
//          Bit4-5 =Spiritomb
//          Bit6-7 =Gible
// $0BAFCB: [NBit] Pokemon Bitflags
//          Bit0-1=Gabite
//          Bit2-3 =Garchomp
//          Bit4-5 =Munchlax
//          Bit6-7 =Riolu
// $0BAFCC: [NBit] Pokemon Bitflags
//          Bit0-1=Lucario
//          Bit2-3 =Hippopotas
//          Bit4-5 =Hippowdon
//          Bit6-7 =Skorupi
// $0BAFCD: [NBit] Pokemon Bitflags
//          Bit0-1=Drapion
//          Bit2-3 =Croagunk
//          Bit4-5 =Toxicraok
//          Bit6-7 =Carnivine
// $0BAFCE: [NBit] Pokemon Bitflags
//          Bit0-1=Finneon
//          Bit2-3 =Lumineon
//          Bit4-5 =Mantyke
//          Bit6-7 =Snover
// $0BAFCF: [NBit] Pokemon Bitflags
//          Bit0-1=Abomasnow
//          Bit2-3 =Weavile
//          Bit4-5 =Magnezone
//          Bit6-7 =LickiLicky
// $0BAFD0: [NBit] Pokemon Bitflags
//          Bit0-1=Rhyperior
//          Bit2-3 =Tangrowth
//          Bit4-5 =Electivire
//          Bit6-7 =Magmortar
// $0BAFD1: [NBit] Pokemon Bitflags
//          Bit0-1=Togekiss
//          Bit2-3 =Yanmega
//          Bit4-5 =Leafeon
//          Bit6-7 =Glaceon
// $0BAFD2: [NBit] Pokemon Bitflags
//          Bit0-1=Gliscor
//          Bit2-3 =Mamoswine
//          Bit4-5 =Porygon-Z
//          Bit6-7 =Gallade
// $0BAFD3: [NBit] Pokemon Bitflags
//          Bit0-1=Probopass
//          Bit2-3 =Dusknoir
//          Bit4-5 =Froslass
// $0BAFD4: [NBit] Pokemon Bitflags
//          Bit6-7 =Dialga
// $0BAFD5: [NBit] Pokemon Bitflags
//          Bit0-1=Palkia
//          Bit2-3 =Heatran
//          Bit4-5 =Regigigas
// $0BAFD6: [NBit] Pokemon Bitflags
//          Bit0-1=Cresselia
//          Bit6-7 =Darkrai
// $0BAFD7: [NBit] Pokemon Bitflags
//          Bit0-1=Shaymin
// $0BAFD8: Browser End
// $0BB194: [8bit] Lifetime Pokemon Captured - Happiny
// $0BB1CF: Next Address = Start of Capture Rank Table.
//          Each Pokemon entry = 2 bits.
//          Ranks:
//          First Bit & Second Bit = 1 - C Rank
//          First Bit = 0 & Second Bit = 1 - B Rank
//          First Bit = 1 & Second Bit = 0 - A Rank
//          First Bit & Second Bit = 0 - S Rank
// $0BB1D1: [NBit] Capture Rank Flags
//          Bit0&1=Charmander
//          Bit2&3=Charmeleon
//          Bit4&5=Charizard
//          Bit6&7=Squirtle
// $0BB1D2: [NBit] Capture Rank Flags
//          Bit0&1=Wartortle
//          Bit2&3=Blastoise
// $0BB1D3: [NBit] Capture Rank Flags
//          Bit2&3=Weedle
//          Bit6&7=Beedrill
// $0BB1D4: [NBit] Capture Rank Flags
//          Bit6&7=Rattata
// $0BB1D5: [NBit] Capture Rank Flags
//          Bit0&1=Raticate
//          Bit2&3=Spearow
//          Bit4&5=Fearow
// $0BB1D6: [NBit] Capture Rank Flags
//          Bit2&3=Pikachu
//          Bit4&5=Raichu
//          Bit6&7=Sandshrew
// $0BB1D7: [NBit] Capture Rank Flags
//          Bit0&1=Sandslash
// $0BB1D9: [NBit] Capture Rank Flags
//          Bit2&3=Vulpix
//          Bit4&5=Ninetales
//          Bit6&7=Jigglypuff
// $0BB1DA: [NBit] Capture Rank Flags
//          Bit0&1=Wigglytuff
//          Bit2&3=Zubat
//          Bit4&5=Golbat
//          Bit6&7=Oddish
// $0BB1DB: [NBit] Capture Rank Flags
//          Bit0&1=Gloom
//          Bit2&3=Vileplume
// $0BB1DE: [NBit] Capture Rank Flags
//          Bit0&1=Mankey
//          Bit2&3=Primeape
//          Bit4&5=Growlithe
//          Bit6&7=Arcanine
// $0BB1DF: [NBit] Capture Rank Flags
//          Bit6&7=Abra
// $0BB1E0: [NBit] Capture Rank Flags
//          Bit2&3=Alakazam
//          Bit4&5=Machop
//          Bit6&7=Machoke
// $0BB1E1: [NBit] Capture Rank Flags
//          Bit0&1=Machamp
//          Bit6&7=Victreebel
// $0BB1E2: [NBit] Capture Rank Flags
//          Bit2&3=Tentacruel
//          Bit4&5=Geodude
//          Bit6&7=Graveler
// $0BB1E3: [NBit] Capture Rank Flags
//          Bit0&1=Golem
//          Bit2&3=Ponyta
//          Bit4&5=Rapidash
// $0BB1E4: [NBit] Capture Rank Flags
//          Bit2&3=Magnemite
//          Bit4&5=Magneton
// $0BB1E5: [NBit] Capture Rank Flag
//          Bit0&1=Doduo
//          Bit2&3=Dodrio
// $0BB1E6: [NBIt] Capjture Rank Flags
//          Bit2&3=Muk
// $0BB1E7: [NBit] Capture Rank Flags
//          Bit0&1=Gastly
//          Bit2&3=Haunter
//          Bit4&5=Gengar
// $0BB1E8: [NBit] Capture Rank Flags
//          Bit0&1=Drowzee
//          Bit2&3=Hypno
// $0BB1E9: [NBit] Capture Rank Flags
//          Bit0&1=Voltorb
//          Bit2&3=Electrode
// $0BB1EB: [NBit] Capture Rank Flags
//          Bit2&3=Koffing
//          Bit4&5=Weezing
//          Bit6&7=Rhyhorn
// $0BB1EC: [NBit] Capture Rank Flags
//          Bit0&1=Rhydon
//          Bit6&7=Kangaskhan
// $0BB1ED: [NBit] Capture Rank Flags
//          Bit0&1=Horsea
//          Bit2&3=Seadra
// $0BB1EE: [NBit] Capture Rank Flags
//          Bit0&1=Staryu
//          Bit2&3=Starmie
//          Bit4&5=Mr. Mime
//          Bit6&7=Scyther
// $0BB1EF: [NBit] Capture Rank Flags
//          Bit0&1=Jynx
//          Bit2&3=Electabuzz
//          Bit4&5=Magmar
//          Bit6&7=Pinsir
// $0BB1F0: [NBit] Capture Rank Flags
//          Bit0&1=Tauros
// $0BB1F1: [NBit] Capture Rank Flags
//          Bit2&3=Eevee
//          Bit4&5=Vaporeon
//          Bit6&7=Jolteon
// $0BB1F2: [NBit] Capture Rank Flags
//          Bit0&1=Flareon
//          Bit4&5=Omanyte
//          Bit6&7=Omastar
// $0BB1F3: [NBit] Capture Rank Flags
//          Bit4&5=Aerodactyl
// $0BB1F4: [NBit] Capture Rank Flags
//          Bit6&7=Dratini
// $0BB1F5: [NBit] Capture Rank Flags
//          Bit0&1=Dragonair
// $0BB1F9: [NBit] Capture Rank Flags
//          Bit6&7=Spinarak
// $0BB1FA: [NBit] Capture Rank Flags
//          Bit0&1=Ariados
//          Bit2&3=Crobat
//          Bit4&5=Chinchou
//          Bit6&7=Lanturn
// $0BB1FB: [NBit] Capture Rank Flags
//          Bit0&1=Pichu
// $0BB1FC: [NBit] Capture Rank Flags
//          Bit6&7=Mareep
// $0BB1FD: [NBit] Capture Rank Flags
//          Bit0&1=Flaaffy
//          Bit2&3=Ampharos
//          Bit4&5=Bellossom
// $0BB1FE: [NBit] Capture Rank Flags
//          Bit2&3=Sudowoodo
// $0BB1FF: [NBit] Capture Rank Flags
//          Bit4&5=Aipom
// $0BB200: [NBit] Capture Rank Flags
//          Bit2&3=Yanma
// $0BB201: [NBit] Capture Rank Flags
//          Bit0&1=Espeon
//          Bit2&3=Umbreon
//          Bit4&5=Murkrow
// $0BB202: [NBit] Capture Rank Flags
//          Bit0&1=Misdreavus
//          Bit6&7=Girafarig
// $0BB203: [NBit] Capture Rank Flags
//          Bit0&1=Pineco
//          Bit2&3=Forretress
//          Bit6&7=Gligar
// $0BB204: [NBit] Capture Rank Flags
//          Bit6&7=Qwilfish
// $0BB205: [NBit] Capture Rank Flags
//          Bit0&1=Scizor
//          Bit6&7=Sneasel
// $0BB206: [NBit] Capture Rank Flags
//          Bit4&5=Slugma
//          Bit6&7=Magcargo
// $0BB207: [NBit] Capture Rank Flags
//          Bit0&1=Swinub
//          Bit2&3=Piloswine
//          Bit4&5=Corsola
// $0BB208: [NBit] Capture Rank Flags
//          Bit2&3=Delibird
//          Bit4&5=Mantine
//          Bit6&7=Skarmory
// $0BB209: [NBit] Capture Rank Flags
//          Bit0&1=Houndour
//          Bit2&3=Houndoom
//          Bit4&5=Kingdra
// $0BB20B: [NBit] Capture Rank Flags
//          Bit0&1=Tyrogue
//          Bit6&7=Elekid
// $0BB20C: [NBit] Capture Rank Flags
//          Bit0&1=Magby
//          Bit2&3=Miltank
// $0BB20D: [NBit] Capture Rank Flags
//          Bit4&5=Larvitar
//          Bit6&7=Pupitar
// $0BB20E: [NBit] Capture Rank Flags
//          Bit0&1=Tyranitar
//          Bit6&7=Celebi
// $0BB20F: [NBit] Capture Rank Flags
//          Bit4&5=Sceptile
// $0BB210: [NBit] Capture Rank Flags
//          Bit2&3=Blaziken
// $0BB214: [NBit] Capture Rank Flags
//          Bit2&3=Seedot
//          Bit4&5=Nuzleaf
//          Bit6&7=Shiftry
// $0BB215: [NBit] Capture Rank Flags
//          Bit0&1=Tailow
//          Bit2&3=Swellow
//          Bit4&5=Wingull
//          Bit6&7=Pelipper
// $0BB216: [NBit] Capture Rank Flags
//          Bit0&1=Ralts
//          Bit2&3=Kirlia
//          Bit4&5=Gardevoir
// $0BB217: [NBit] Capture Rank Flags
//          Bit6&7=Slakoth
// $0BB218: [NBit] Capture Rank Flags
//          Bit6&7=Ninjask
// $0BB21A: [NBit] Capture Rank Flags
//          Bit0&1=Makuhita
//          Bit2&3=Hariyama
//          Bit6&7=Nosepass
// $0BB21B: [NBit] Capture Rank Flags
//          Bit4&5=Sableye
//          Bit6&7=Mawile
// $0BB21C: [NBit] Capture Rank Flags
//          Bit0&1=Aron
//          Bit2&3=Lairon
//          Bit4&5=Aggron
// $0BB21E: [NBit] Capture Rank Flags
//          Bit6&7=Roselia
// $0BB21F: [NBit] Capture Rank Flags
//          Bit6&7=Sharpedo
// $0BB220: [NBit] Capture Rank Flags
//          Bit0&1=Wailmer
//          Bit2&3=Wailord (NULL)
//          Bit4&5=Numel
//          Bit6&7=Camerupt
// $0BB221: [NBit] Capture Rank Flags
//          Bit0&1=Torkoal
// $0BB222: [NBit] Capture Rank Flags
//          Bit4&5=Flygon
//          Bit6&7=Cacnea
// $0BB223: [NBit] Capture Rank Flags
//          Bit0&1=Cacturne
//          Bit4&5=Altaria
// $0BB226: [NBit] Capture Rank Flags
//          Bit0&1=Claydol
// $0BB228: [NBit] Capture Rank Flags
//          Bit2&3=Shuppet
//          Bit4&5=Banette
//          Bit6&7=Duskull
// $0BB229: [NBit] Capture Rank Flags
//          Bit0&1=Dusclops
//          Bit6&7=Absol
// $0BB22A: [NBit] Capture Rank Flags
//          Bit2&3=Snorunt
//          Bit4&5=Glalie
//          Bit6&7=Spheal
// $0BB22B: [NBit] Capture Rank Flags
//          Bit0&1=Sealeo
//          Bit2&3=Walrein
//          Bit6&7=Huntail
// $0BB22C: [NBit] Capure Rank Flags
//          Bit0&1=Gorebyss
//          Bit6&7=Bagon
// $0BB22D: [NBit] Capture Rank Flags
//          Bit0&1=Shelgon
//          Bit2&3=Salamence
// $0BB22E: [NBit] Capture Rank Flags
//          Bit2&3=Regirock
//          Bit4&5=Regice
//          Bit6&7=Registeel
// $0BB230: [NBit] Capture Rank Flags
//          Bit6&7=Turtwig
// $0BB231: [NBit] Capture Rank Flags
//          Bit0&1=Grotle
//          Bit2&3=Torterra
//          Bit4&5=Chimchar
//          Bit6&7=Monferno
// $0BB232: [NBit] Capture Rank Flags
//          Bit0&1=Infernape
//          Bit2&3=Piplup
//          Bit4&5=Prinplup
//          Bit6&7=Empoleon
// $0BB233: [NBit] Capture Rank Flags
//          Bit0&1=Starly
//          Bit2&3=Staravia
//          Bit4&5=Staraptor
//          Bit6&7=Bidoof
// $0BB234: [NBit] Capture Rank Flags
//          Bit0&1=Bibarel
//          Bit2&3=Kricketot
//          Bit4&5=Kricketune
//          Bit6&7=Shinx
// $0BB235: [NBit] Capture Rank Flags
//          Bit0&1=Luxio
//          Bit2&3=Luxray
//          Bit4&5=Budew
//          Bit6&7=Roserade
// $0BB236: [NBit] Capture Rank Flags
//          Bit0&1=Cranidos
//          Bit2&3=Rampardos
//          Bit4&5=Shieldon
//          Bit6&7=Bastiodon
// $0BB237: [NBit] Capture Rank Flags
//          Bit4&5=Mothim
//          Bit6&7=Combee
// $0BB238: [NBit] Capture Rank Flags
//          Bit0&1=Vespiquen
//          Bit2&3=Pachirisu
//          Bit4&5=Buizel
//          Bit6&7=Floatzel
// $0BB239: [NBit] Capture Rank Flags
//          Bit0&1=Cherubi
//          Bit2&3=Cherrim
//          Bit4&5=Shellos
//          Bit6&7=Gastrodon
// $0BB23A: [NBit] Capture Rank Flags
//          Bit0&1=Ambipom
//          Bit2&3=Drifloon
//          Bit4&5=Drifblim
//          Bit6&7=Buneary
// $0BB23B: [NBit] Capture Rank Flags
//          Bit0&1=Lopunny
//          Bit2&3=Mismagius
//          Bit4&5=Honchkrow
//          Bit6&7=Glameow
// $0BB23C: [NBit] Capture Rank Flags
//          Bit0&1=Purugly
//          Bit2&3=Chingling
//          Bit4&5=Stunky
//          Bit6&7=Skuntank
// $0BB23D: [NBit] Capture Rank Flags
//          Bit0&1=Bronzor
//          Bit2&3=Bronzong
//          Bit4&5=Bonsly
//          Bit6&7=Mime Jr.
// $0BB23E: [NBit] Capture Rank Flags
//          Bit0&1=Happiny
//          Bit2&3=Chatot
//          Bit4&5=Spiritomb
//          Bit6&7=Gible
// $0BB23F: [NBit] Capture Rank Flags
//          Bit0&1=Gabite
//          Bit2&3=Garchomp
//          Bit4&5=Munchlax
//          Bit6&7=Riolu
// $0BB240: [NBit] Capture Rank Flags
//          Bit0&1=Lucario
//          Bit2&3=Hippopotas
//          Bit4&5=Hippowdon
//          Bit6&7=Skorupi
// $0BB241: [NBit] Capture Rank Flags
//          Bit0&1=Drapion
//          Bit2&3=Croagunk
//          Bit4&5=Toxicroak
//          Bit6&7=Carnivine
// $0BB242: [NBit] Capture Rank Flags
//          Bit0&1=Finneon
//          Bit2&3=Lumineon
//          Bit4&5=Mantyke
//          Bit6&7=Snover
// $0BB243: [NBit] Capture Rank Flags
//          Bit0&1=Abomasnow
//          Bit2&3=Weavile
//          Bit4&5=Magnezone
//          Bit6&7=LickiLicky
// $0BB244: [NBit] Capture Rank Flags
//          Bit0&1=Rhyperior
//          Bit2&3=Tangrowth
//          Bit4&5=Electivire
//          Bit6&7=Magmortar
// $0BB245: [NBit] Capture Rank Flags
//          Bit0&1=Togekiss
//          Bit2&3=Yanmega
//          Bit4&5=Leafeon
//          Bit6&7=Galceon
// $0BB246: [NBit] Capture Rank Flags
//          Bit0&1=Gliscor
//          Bit2&3=Mamoswine
//          Bit4&5=Porygon-Z
//          Bit6&7=Gallade
// $0BB247: [NBit] Capture Rank Flags
//          Bit0&1=Probopass
//          Bit2&3=Dusknoir
//          Bit4&5=Froslass
// $0BB248: [NBit] Capture Rank Flags
//          Bit6&7=Dialga
// $0BB249: [NBit] Capture Rank Flags
//          Bit0&1=Palkia
//          Bit2&3=Heatran
//          Bit4&5=Regigigas
// $0BB24A: [NBit] Capture Rank Flags
//          Bit0&1=Cresselia
//          Bit6&7=Darkrai
// $0BB24B: [NBit] Capture Rank Flags
//          Bit0&1=Shaymin
pokemon_database = {
    "Pichu":{"dex_one":bit0(0x0BAF87), "dex_two":bit1(0x0BAF87), "cptr_one":bit0(0x0BB1FB), "cptr_two":bit1(0x0BB1FB)},
    "Pikachu":{"dex_one":bit2(0x0BAF62), "dex_two":bit3(0x0BAF62), "cptr_one":bit2(0x0BB1D6), "cptr_two":bit3(0x0BB1D6)},
    "Raichu":{"dex_one":bit4(0x0BAF62), "dex_two":bit5(0x0BAF62), "cptr_one":bit4(0x0BB1D6), "cptr_two":bit5(0x0BB1D6)},
    "Bidoof":{"dex_one":bit6(0x0BAFBF), "dex_two":bit7(0x0BAFBF), "cptr_one":bit6(0x0BB233), "cptr_two":bit7(0x0BB233)},
    "Bibarel":{"dex_one":bit0(0x0BAFC0), "dex_two":bit1(0x0BAFC0), "cptr_one":bit0(0x0BB234), "cptr_two":bit1(0x0BB234)},
    "Taillow":{"dex_one":bit0(0x0BAFA1), "dex_two":bit1(0x0BAFA1), "cptr_one":bit0(0x0BB215), "cptr_two":bit1(0x0BB215)},
    "Swellow":{"dex_one":bit2(0x0BAFA1), "dex_two":bit3(0x0BAFA1), "cptr_one":bit2(0x0BB215), "cptr_two":bit3(0x0BB215)},
    "Budew":{"dex_one":bit4(0x0BAFC1), "dex_two":bit5(0x0BAFC1), "cptr_one":bit4(0x0BB235), "cptr_two":bit5(0x0BB235)},
    "Roselia":{"dex_one":bit6(0x0BAFAA), "dex_two":bit7(0x0BAFAA), "cptr_one":bit6(0x0BB21E), "cptr_two":bit7(0x0BB21E)},
    "Roserade":{"dex_one":bit6(0x0BAFC1), "dex_two":bit7(0x0BAFC1), "cptr_one":bit6(0x0BB235), "cptr_two":bit7(0x0BB235)},
    "Squirtle":{"dex_one":bit6(0x0BAF5D), "dex_two":bit7(0x0BAF5D), "cptr_one":bit6(0x0BB1D1), "cptr_two":bit7(0x0BB1D1)},
    "Wartortle":{"dex_one":bit0(0x0BAF5E), "dex_two":bit1(0x0BAF5E), "cptr_one":bit0(0x0BB1D2), "cptr_two":bit1(0x0BB1D2)},
    "Blastoise":{"dex_one":bit2(0x0BAF5E), "dex_two":bit3(0x0BAF5E), "cptr_one":bit2(0x0BB1D2), "cptr_two":bit3(0x0BB1D2)},
    "Zubat":{"dex_one":bit2(0x0BAF66), "dex_two":bit3(0x0BAF66), "cptr_one":bit2(0x0BB1DA), "cptr_two":bit3(0x0BB1DA)},
    "Golbat":{"dex_one":bit4(0x0BAF66), "dex_two":bit5(0x0BAF66), "cptr_one":bit4(0x0BB1DA), "cptr_two":bit5(0x0BB1DA)},
    "Crobat":{"dex_one":bit2(0x0BAF86), "dex_two":bit3(0x0BAF86), "cptr_one":bit2(0x0BB1FA), "cptr_two":bit3(0x0BB1FA)},
    "Gastly":{"dex_one":bit0(0x0BAF73), "dex_two":bit1(0x0BAF73), "cptr_one":bit0(0x0BB1E7), "cptr_two":bit1(0x0BB1E7)},
    "Haunter":{"dex_one":bit2(0x0BAF73), "dex_two":bit3(0x0BAF73), "cptr_one":bit2(0x0BB1E7), "cptr_two":bit3(0x0BB1E7)},
    "Gengar":{"dex_one":bit4(0x0BAF73), "dex_two":bit5(0x0BAF73), "cptr_one":bit4(0x0BB1E7), "cptr_two":bit5(0x0BB1E7)},
    "Buneary":{"dex_one":bit6(0x0BAFC6), "dex_two":bit7(0x0BAFC6), "cptr_one":bit6(0x0BB23A), "cptr_two":bit7(0x0BB23A)},
    "Lopunny":{"dex_one":bit0(0x0BAFC7), "dex_two":bit1(0x0BAFC7), "cptr_one":bit0(0x0BB23B), "cptr_two":bit1(0x0BB23B)},
    "Happiny":{"dex_one":bit0(0x0BAFCA), "dex_two":bit1(0x0BAFCA), "cptr_one":bit0(0x0BB23E), "cptr_two":bit1(0x0BB23E)},
    "Starly":{"dex_one":bit0(0x0BAFBF), "dex_two":bit1(0x0BAFBF), "cptr_one":bit0(0x0BB233), "cptr_two":bit1(0x0BB233)},
    "Staravia":{"dex_one":bit2(0x0BAFBF), "dex_two":bit3(0x0BAFBF), "cptr_one":bit2(0x0BB233), "cptr_two":bit3(0x0BB233)},
    "Staraptor":{"dex_one":bit4(0x0BAFBF), "dex_two":bit5(0x0BAFBF), "cptr_one":bit4(0x0BB233), "cptr_two":bit5(0x0BB233)},
    "Pachirisu":{"dex_one":bit2(0x0BAFC4), "dex_two":bit3(0x0BAFC4), "cptr_one":bit2(0x0BB238), "cptr_two":bit3(0x0BB238)},
    "Munchlax":{"dex_one":bit4(0x0BAFCB), "dex_two":bit5(0x0BAFCB), "cptr_one":bit4(0x0BB23F), "cptr_two":bit5(0x0BB23F)},
    "Makuhita":{"dex_one":bit0(0x0BAFA6), "dex_two":bit1(0x0BAFA6), "cptr_one":bit0(0x0BB21A), "cptr_two":bit1(0x0BB21A)},
    "Hariyama":{"dex_one":bit2(0x0BAFA6), "dex_two":bit3(0x0BAFA6), "cptr_one":bit2(0x0BB21A), "cptr_two":bit3(0x0BB21A)},
    "Bonsly":{"dex_one":bit4(0x0BAFC9), "dex_two":bit5(0x0BAFC9), "cptr_one":bit4(0x0BB23D), "cptr_two":bit5(0x0BB23D)},
    "Sudowoodo":{"dex_one":bit2(0x0BAF8A), "dex_two":bit3(0x0BAF8A), "cptr_one":bit2(0x0BB1FE), "cptr_two":bit3(0x0BB1FE)},
    "Slakoth":{"dex_one":bit6(0x0BAFA3), "dex_two":bit7(0x0BAFA3), "cptr_one":bit6(0x0BB217), "cptr_two":bit7(0x0BB217)},
    "Seedot":{"dex_one":bit2(0x0BAFA0), "dex_two":bit3(0x0BAFA0), "cptr_one":bit2(0x0BB214), "cptr_two":bit3(0x0BB214)},
    "Nuzleaf":{"dex_one":bit4(0x0BAFA0), "dex_two":bit5(0x0BAFA0), "cptr_one":bit4(0x0BB214), "cptr_two":bit5(0x0BB214)},
    "Shiftry":{"dex_one":bit6(0x0BAFA0), "dex_two":bit7(0x0BAFA0), "cptr_one":bit6(0x0BB214), "cptr_two":bit7(0x0BB214)},
    "Tangrowth":{"dex_one":bit2(0x0BAFD0), "dex_two":bit3(0x0BAFD0), "cptr_one":bit2(0x0BB244), "cptr_two":bit3(0x0BB244)},
    "Shellos":{"dex_one":bit4(0x0BAFC5), "dex_two":bit5(0x0BAFC5), "cptr_one":bit4(0x0BB239), "cptr_two":bit5(0x0BB239)},
    "Gastrodon":{"dex_one":bit6(0x0BAFC5), "dex_two":bit7(0x0BAFC5), "cptr_one":bit6(0x0BB239), "cptr_two":bit7(0x0BB239)},
    "Glameow":{"dex_one":bit6(0x0BAFC7), "dex_two":bit7(0x0BAFC7), "cptr_one":bit6(0x0BB23B), "cptr_two":bit7(0x0BB23B)},
    "Purugly":{"dex_one":bit0(0x0BAFC8), "dex_two":bit1(0x0BAFC8), "cptr_one":bit0(0x0BB23C), "cptr_two":bit1(0x0BB23C)},
    "Geodude":{"dex_one":bit4(0x0BAF6E), "dex_two":bit5(0x0BAF6E), "cptr_one":bit4(0x0BB1E2), "cptr_two":bit5(0x0BB1E2)},
    "Graveler":{"dex_one":bit6(0x0BAF6E), "dex_two":bit7(0x0BAF6E), "cptr_one":bit6(0x0BB1E2), "cptr_two":bit7(0x0BB1E2)},
    "Golem":{"dex_one":bit0(0x0BAF6F), "dex_two":bit1(0x0BAF6F), "cptr_one":bit0(0x0BB1E3), "cptr_two":bit1(0x0BB1E3)},
    "Nosepass":{"dex_one":bit6(0x0BAFA6), "dex_two":bit7(0x0BAFA6), "cptr_one":bit6(0x0BB21A), "cptr_two":bit7(0x0BB21A)},
    "Probopass":{"dex_one":bit0(0x0BAFD3), "dex_two":bit1(0x0BAFD3), "cptr_one":bit0(0x0BB247), "cptr_two":bit1(0x0BB247)},
    "Miltank":{"dex_one":bit2(0x0BAF98), "dex_two":bit3(0x0BAF98), "cptr_one":bit2(0x0BB20C), "cptr_two":bit3(0x0BB20C)},
    "Cherubi":{"dex_one":bit0(0x0BAFC5), "dex_two":bit1(0x0BAFC5), "cptr_one":bit0(0x0BB239), "cptr_two":bit1(0x0BB239)},
    "Cherrim":{"dex_one":bit2(0x0BAFC5), "dex_two":bit3(0x0BAFC5), "cptr_one":bit2(0x0BB239), "cptr_two":bit3(0x0BB239)},
    "Shinx":{"dex_one":bit6(0x0BAFC0), "dex_two":bit7(0x0BAFC0), "cptr_one":bit6(0x0BB234), "cptr_two":bit7(0x0BB234)},
    "Luxio":{"dex_one":bit0(0x0BAFC1), "dex_two":bit1(0x0BAFC1), "cptr_one":bit0(0x0BB235), "cptr_two":bit1(0x0BB235)},
    "Luxray":{"dex_one":bit2(0x0BAFC1), "dex_two":bit3(0x0BAFC1), "cptr_one":bit2(0x0BB235), "cptr_two":bit3(0x0BB235)},
    "Turtwig":{"dex_one":bit6(0x0BAFBC), "dex_two":bit7(0x0BAFBC), "cptr_one":bit6(0x0BB230), "cptr_two":bit7(0x0BB230)},
    "Grotle":{"dex_one":bit0(0x0BAFBD), "dex_two":bit1(0x0BAFBD), "cptr_one":bit0(0x0BB231), "cptr_two":bit1(0x0BB231)},
    "Torterra":{"dex_one":bit2(0x0BAFBD), "dex_two":bit3(0x0BAFBD), "cptr_one":bit2(0x0BB231), "cptr_two":bit3(0x0BB231)},
    "Buizel":{"dex_one":bit4(0x0BAFC4), "dex_two":bit5(0x0BAFC4), "cptr_one":bit4(0x0BB238), "cptr_two":bit5(0x0BB238)},
    "Floatzel":{"dex_one":bit6(0x0BAFC4), "dex_two":bit7(0x0BAFC4), "cptr_one":bit6(0x0BB238), "cptr_two":bit7(0x0BB238)},
    "Weedle":{"dex_one":bit2(0x0BAF5F), "dex_two":bit3(0x0BAF5F), "cptr_one":bit2(0x0BB1D3), "cptr_two":bit3(0x0BB1D3)},
    "Beedrill":{"dex_one":bit6(0x0BAF5F), "dex_two":bit7(0x0BAF5F), "cptr_one":bit6(0x0BB1D3), "cptr_two":bit7(0x0BB1D3)},
    "Combee":{"dex_one":bit6(0x0BAFC3), "dex_two":bit7(0x0BAFC3), "cptr_one":bit6(0x0BB237), "cptr_two":bit7(0x0BB237)},
    "Vespiquen":{"dex_one":bit0(0x0BAFC4), "dex_two":bit1(0x0BAFC4), "cptr_one":bit0(0x0BB238), "cptr_two":bit1(0x0BB238)},
    "Tyrogue":{"dex_one":bit0(0x0BAF97), "dex_two":bit1(0x0BAF97), "cptr_one":bit0(0x0BB20B), "cptr_two":bit1(0x0BB20B)},
    "Magnemite":{"dex_one":bit2(0x0BAF70), "dex_two":bit3(0x0BAF70), "cptr_one":bit2(0x0BB1E4), "cptr_two":bit3(0x0BB1E4)},
    "Magneton":{"dex_one":bit4(0x0BAF70), "dex_two":bit5(0x0BAF70), "cptr_one":bit4(0x0BB1E4), "cptr_two":bit5(0x0BB1E4)},
    "Magnezone":{"dex_one":bit4(0x0BAFCF), "dex_two":bit5(0x0BAFCF), "cptr_one":bit4(0x0BB243), "cptr_two":bit5(0x0BB243)},
    "Growlithe":{"dex_one":bit4(0x0BAF6A), "dex_two":bit5(0x0BAF6A), "cptr_one":bit4(0x0BB1DE), "cptr_two":bit5(0x0BB1DE)},
    "Arcanine":{"dex_one":bit6(0x0BAF6A), "dex_two":bit7(0x0BAF6A), "cptr_one":bit6(0x0BB1DE), "cptr_two":bit7(0x0BB1DE)},
    "Rattata":{"dex_one":bit6(0x0BAF60), "dex_two":bit7(0x0BAF60), "cptr_one":bit6(0x0BB1D4), "cptr_two":bit7(0x0BB1D4)},
    "Raticate":{"dex_one":bit0(0x0BAF61), "dex_two":bit1(0x0BAF61), "cptr_one":bit0(0x0BB1D5), "cptr_two":bit1(0x0BB1D5)},
    "Chatot":{"dex_one":bit2(0x0BAFCA), "dex_two":bit3(0x0BAFCA), "cptr_one":bit2(0x0BB23E), "cptr_two":bit3(0x0BB23E)},
    "Elekid":{"dex_one":bit6(0x0BAF97), "dex_two":bit7(0x0BAF97), "cptr_one":bit6(0x0BB20B), "cptr_two":bit7(0x0BB20B)},
    "Electabuzz":{"dex_one":bit2(0x0BAF7B), "dex_two":bit3(0x0BAF7B), "cptr_one":bit2(0x0BB1EF), "cptr_two":bit3(0x0BB1EF)},
    "Electivire":{"dex_one":bit4(0x0BAFD0), "dex_two":bit5(0x0BAFD0), "cptr_one":bit4(0x0BB244), "cptr_two":bit5(0x0BB244)},
    "Magby":{"dex_one":bit0(0x0BAF98), "dex_two":bit1(0x0BAF98), "cptr_one":bit0(0x0BB20C), "cptr_two":bit1(0x0BB20C)},
    "Magmar":{"dex_one":bit4(0x0BAF7B), "dex_two":bit5(0x0BAF7B), "cptr_one":bit4(0x0BB1EF), "cptr_two":bit5(0x0BB1EF)},
    "Magmortar":{"dex_one":bit6(0x0BAFD0), "dex_two":bit7(0x0BAFD0), "cptr_one":bit6(0x0BB244), "cptr_two":bit7(0x0BB244)},
    "Voltorb":{"dex_one":bit0(0x0BAF75), "dex_two":bit1(0x0BAF75), "cptr_one":bit0(0x0BB1E9), "cptr_two":bit1(0x0BB1E9)},
    "Electrode":{"dex_one":bit2(0x0BAF75), "dex_two":bit3(0x0BAF75), "cptr_one":bit2(0x0BB1E9), "cptr_two":bit3(0x0BB1E9)},
    "Wingull":{"dex_one":bit4(0x0BAFA1), "dex_two":bit5(0x0BAFA1), "cptr_one":bit4(0x0BB215), "cptr_two":bit5(0x0BB215)},
    "Pelipper":{"dex_one":bit6(0x0BAFA1), "dex_two":bit7(0x0BAFA1), "cptr_one":bit6(0x0BB215), "cptr_two":bit7(0x0BB215)},
    "Croagunk":{"dex_one":bit2(0x0BAFCD), "dex_two":bit3(0x0BAFCD), "cptr_one":bit2(0x0BB241), "cptr_two":bit3(0x0BB241)},
    "Toxicroak":{"dex_one":bit4(0x0BAFCD), "dex_two":bit5(0x0BAFCD), "cptr_one":bit4(0x0BB241), "cptr_two":bit5(0x0BB241)},
    "Kricketot":{"dex_one":bit2(0x0BAFC0), "dex_two":bit3(0x0BAFC0), "cptr_one":bit2(0x0BB234), "cptr_two":bit3(0x0BB234)},
    "Kricketune":{"dex_one":bit4(0x0BAFC0), "dex_two":bit5(0x0BAFC0), "cptr_one":bit4(0x0BB234), "cptr_two":bit5(0x0BB234)},
    "Cranidos":{"dex_one":bit0(0x0BAFC2), "dex_two":bit1(0x0BAFC2), "cptr_one":bit0(0x0BB236), "cptr_two":bit1(0x0BB236)},
    "Rampardos":{"dex_one":bit2(0x0BAFC2), "dex_two":bit3(0x0BAFC2), "cptr_one":bit2(0x0BB236), "cptr_two":bit3(0x0BB236)},
    "Finneon":{"dex_one":bit0(0x0BAFCE), "dex_two":bit1(0x0BAFCE), "cptr_one":bit0(0x0BB242), "cptr_two":bit1(0x0BB242)},
    "Lumineon":{"dex_one":bit2(0x0BAFCE), "dex_two":bit3(0x0BAFCE), "cptr_one":bit2(0x0BB242), "cptr_two":bit3(0x0BB242)},
    "Chinchou":{"dex_one":bit4(0x0BAF86), "dex_two":bit5(0x0BAF86), "cptr_one":bit4(0x0BB1FA), "cptr_two":bit5(0x0BB1FA)},
    "Lanturn":{"dex_one":bit6(0x0BAF86), "dex_two":bit7(0x0BAF86), "cptr_one":bit6(0x0BB1FA), "cptr_two":bit7(0x0BB1FA)},
    "Mantyke":{"dex_one":bit4(0x0BAFCE), "dex_two":bit5(0x0BAFCE), "cptr_one":bit4(0x0BB242), "cptr_two":bit5(0x0BB242)},
    "Mantine":{"dex_one":bit4(0x0BAF94), "dex_two":bit5(0x0BAF94), "cptr_one":bit4(0x0BB208), "cptr_two":bit5(0x0BB208)},
    "Qwilfish":{"dex_one":bit6(0x0BAF90), "dex_two":bit7(0x0BAF90), "cptr_one":bit6(0x0BB204), "cptr_two":bit7(0x0BB204)},
    "Corsola":{"dex_one":bit4(0x0BAF93), "dex_two":bit5(0x0BAF93), "cptr_one":bit4(0x0BB207), "cptr_two":bit5(0x0BB207)},
    "Staryu":{"dex_one":bit0(0x0BAF7A), "dex_two":bit1(0x0BAF7A), "cptr_one":bit0(0x0BB1EE), "cptr_two":bit1(0x0BB1EE)},
    "Starmie":{"dex_one":bit2(0x0BAF7A), "dex_two":bit3(0x0BAF7A), "cptr_one":bit2(0x0BB1EE), "cptr_two":bit3(0x0BB1EE)},
    "Sharpedo":{"dex_one":bit6(0x0BAFAB), "dex_two":bit7(0x0BAFAB), "cptr_one":bit6(0x0BB21F), "cptr_two":bit7(0x0BB21F)},
    "Eevee":{"dex_one":bit2(0x0BAF7D), "dex_two":bit3(0x0BAF7D), "cptr_one":bit2(0x0BB1F1), "cptr_two":bit3(0x0BB1F1)},
    "Vaporeon":{"dex_one":bit4(0x0BAF7D), "dex_two":bit5(0x0BAF7D), "cptr_one":bit4(0x0BB1F1), "cptr_two":bit5(0x0BB1F1)},
    "Jolteon":{"dex_one":bit6(0x0BAF7D), "dex_two":bit7(0x0BAF7D), "cptr_one":bit6(0x0BB1F1), "cptr_two":bit7(0x0BB1F1)},
    "Flareon":{"dex_one":bit0(0x0BAF7E), "dex_two":bit1(0x0BAF7E), "cptr_one":bit0(0x0BB1F2), "cptr_two":bit1(0x0BB1F2)},
    "Espeon":{"dex_one":bit0(0x0BAF8D), "dex_two":bit1(0x0BAF8D), "cptr_one":bit0(0x0BB201), "cptr_two":bit1(0x0BB201)},
    "Umbreon":{"dex_one":bit2(0x0BAF8D), "dex_two":bit3(0x0BAF8D), "cptr_one":bit2(0x0BB201), "cptr_two":bit3(0x0BB201)},
    "Leafeon":{"dex_one":bit4(0x0BAFD1), "dex_two":bit5(0x0BAFD1), "cptr_one":bit4(0x0BB245), "cptr_two":bit5(0x0BB245)},
    "Glaceon":{"dex_one":bit6(0x0BAFD1), "dex_two":bit7(0x0BAFD1), "cptr_one":bit6(0x0BB245), "cptr_two":bit7(0x0BB245)},
    "Mareep":{"dex_one":bit6(0x0BAF88), "dex_two":bit7(0x0BAF88), "cptr_one":bit6(0x0BB1FC), "cptr_two":bit7(0x0BB1FC)},
    "Flaaffy":{"dex_one":bit0(0x0BAF89), "dex_two":bit1(0x0BAF89), "cptr_one":bit0(0x0BB1FD), "cptr_two":bit1(0x0BB1FD)},
    "Ampharos":{"dex_one":bit2(0x0BAF89), "dex_two":bit3(0x0BAF89), "cptr_one":bit2(0x0BB1FD), "cptr_two":bit3(0x0BB1FD)},
    "Aipom":{"dex_one":bit4(0x0BAF8B), "dex_two":bit5(0x0BAF8B), "cptr_one":bit4(0x0BB1FF), "cptr_two":bit5(0x0BB1FF)},
    "Ambipom":{"dex_one":bit0(0x0BAFC6), "dex_two":bit1(0x0BAFC6), "cptr_one":bit0(0x0BB23A), "cptr_two":bit1(0x0BB23A)},
    "Pineco":{"dex_one":bit0(0x0BAF8F), "dex_two":bit1(0x0BAF8F), "cptr_one":bit0(0x0BB203), "cptr_two":bit1(0x0BB203)},
    "Forretress":{"dex_one":bit2(0x0BAF8F), "dex_two":bit3(0x0BAF8F), "cptr_one":bit2(0x0BB203), "cptr_two":bit3(0x0BB203)},
    "Spearow":{"dex_one":bit2(0x0BAF61), "dex_two":bit3(0x0BAF61), "cptr_one":bit2(0x0BB1D5), "cptr_two":bit3(0x0BB1D5)},
    "Fearow":{"dex_one":bit4(0x0BAF61), "dex_two":bit5(0x0BAF61), "cptr_one":bit4(0x0BB1D5), "cptr_two":bit5(0x0BB1D5)},
    "Oddish":{"dex_one":bit6(0x0BAF66), "dex_two":bit7(0x0BAF66), "cptr_one":bit6(0x0BB1DA), "cptr_two":bit7(0x0BB1DA)},
    "Gloom":{"dex_one":bit0(0x0BAF67), "dex_two":bit1(0x0BAF67), "cptr_one":bit0(0x0BB1DB), "cptr_two":bit1(0x0BB1DB)},
    "Vileplume":{"dex_one":bit2(0x0BAF67), "dex_two":bit3(0x0BAF67), "cptr_one":bit2(0x0BB1DB), "cptr_two":bit3(0x0BB1DB)},
    "Bellossom":{"dex_one":bit4(0x0BAF89), "dex_two":bit5(0x0BAF89), "cptr_one":bit4(0x0BB1FD), "cptr_two":bit5(0x0BB1FD)},
    "Yanma":{"dex_one":bit2(0x0BAF8C), "dex_two":bit3(0x0BAF8C), "cptr_one":bit2(0x0BB200), "cptr_two":bit3(0x0BB200)},
    "Yanmega":{"dex_one":bit2(0x0BAFD1), "dex_two":bit3(0x0BAFD1), "cptr_one":bit2(0x0BB245), "cptr_two":bit3(0x0BB245)},
    "Larvitar":{"dex_one":bit4(0x0BAF99), "dex_two":bit5(0x0BAF99), "cptr_one":bit4(0x0BB20D), "cptr_two":bit5(0x0BB20D)},
    "Pupitar":{"dex_one":bit6(0x0BAF99), "dex_two":bit7(0x0BAF99), "cptr_one":bit6(0x0BB20D), "cptr_two":bit7(0x0BB20D)},
    "Tyranitar":{"dex_one":bit0(0x0BAF9A), "dex_two":bit1(0x0BAF9A), "cptr_one":bit0(0x0BB20E), "cptr_two":bit1(0x0BB20E)},
    "Pinsir":{"dex_one":bit6(0x0BAF7B), "dex_two":bit7(0x0BAF7B), "cptr_one":bit6(0x0BB1EF), "cptr_two":bit7(0x0BB1EF)},
    "Numel":{"dex_one":bit4(0x0BAFAC), "dex_two":bit5(0x0BAFAC), "cptr_one":bit4(0x0BB220), "cptr_two":bit5(0x0BB220)},
    "Camerupt":{"dex_one":bit6(0x0BAFAC), "dex_two":bit7(0x0BAFAC), "cptr_one":bit6(0x0BB220), "cptr_two":bit7(0x0BB220)},
    "Mankey":{"dex_one":bit0(0x0BAF6A), "dex_two":bit1(0x0BAF6A), "cptr_one":bit0(0x0BB1DE), "cptr_two":bit1(0x0BB1DE)},
    "Primeape":{"dex_one":bit2(0x0BAF6A), "dex_two":bit3(0x0BAF6A), "cptr_one":bit2(0x0BB1DE), "cptr_two":bit3(0x0BB1DE)},
    "Gligar":{"dex_one":bit6(0x0BAF8F), "dex_two":bit7(0x0BAF8F), "cptr_one":bit6(0x0BB203), "cptr_two":bit7(0x0BB203)},
    "Gliscor":{"dex_one":bit0(0x0BAFD2), "dex_two":bit1(0x0BAFD2), "cptr_one":bit0(0x0BB246), "cptr_two":bit1(0x0BB246)},
    "Mawile":{"dex_one":bit6(0x0BAFA7), "dex_two":bit7(0x0BAFA7), "cptr_one":bit6(0x0BB21B), "cptr_two":bit7(0x0BB21B)},
    "Aron":{"dex_one":bit0(0x0BAFA8), "dex_two":bit1(0x0BAFA8), "cptr_one":bit0(0x0BB21C), "cptr_two":bit1(0x0BB21C)},
    "Lairon":{"dex_one":bit2(0x0BAFA8), "dex_two":bit3(0x0BAFA8), "cptr_one":bit2(0x0BB21C), "cptr_two":bit3(0x0BB21C)},
    "Aggron":{"dex_one":bit4(0x0BAFA8), "dex_two":bit5(0x0BAFA8), "cptr_one":bit4(0x0BB21C), "cptr_two":bit5(0x0BB21C)},
    "Doduo":{"dex_one":bit0(0x0BAF71), "dex_two":bit1(0x0BAF71), "cptr_one":bit0(0x0BB1E5), "cptr_two":bit1(0x0BB1E5)},
    "Dodrio":{"dex_one":bit2(0x0BAF71), "dex_two":bit3(0x0BAF71), "cptr_one":bit2(0x0BB1E5), "cptr_two":bit3(0x0BB1E5)},
    "Carnivine":{"dex_one":bit6(0x0BAFCD), "dex_two":bit7(0x0BAFCD), "cptr_one":bit6(0x0BB241), "cptr_two":bit7(0x0BB241)},
    "Charmander":{"dex_one":bit0(0x0BAF5D), "dex_two":bit1(0x0BAF5D), "cptr_one":bit0(0x0BB1D1), "cptr_two":bit1(0x0BB1D1)},
    "Charmeleon":{"dex_one":bit2(0x0BAF5D), "dex_two":bit3(0x0BAF5D), "cptr_one":bit2(0x0BB1D1), "cptr_two":bit3(0x0BB1D1)},
    "Charizard":{"dex_one":bit4(0x0BAF5D), "dex_two":bit5(0x0BAF5D), "cptr_one":bit4(0x0BB1D1), "cptr_two":bit5(0x0BB1D1)},
    "Slugma":{"dex_one":bit4(0x0BAF92), "dex_two":bit5(0x0BAF92), "cptr_one":bit4(0x0BB206), "cptr_two":bit5(0x0BB206)},
    "Magcargo":{"dex_one":bit6(0x0BAF92), "dex_two":bit7(0x0BAF92), "cptr_one":bit6(0x0BB206), "cptr_two":bit7(0x0BB206)},
    "Drifloon":{"dex_one":bit2(0x0BAFC6), "dex_two":bit3(0x0BAFC6), "cptr_one":bit2(0x0BB23A), "cptr_two":bit3(0x0BB23A)},
    "Drifblim":{"dex_one":bit4(0x0BAFC6), "dex_two":bit5(0x0BAFC6), "cptr_one":bit4(0x0BB23A), "cptr_two":bit5(0x0BB23A)},
    "Stunky":{"dex_one":bit4(0x0BAFC8), "dex_two":bit5(0x0BAFC8), "cptr_one":bit4(0x0BB23C), "cptr_two":bit5(0x0BB23C)},
    "Skuntank":{"dex_one":bit6(0x0BAFC8), "dex_two":bit7(0x0BAFC8), "cptr_one":bit6(0x0BB23C), "cptr_two":bit7(0x0BB23C)},
    "Kangaskhan":{"dex_one":bit6(0x0BAF78), "dex_two":bit7(0x0BAF78), "cptr_one":bit6(0x0BB1EC), "cptr_two":bit7(0x0BB1EC)},
    "Shuppet":{"dex_one":bit2(0x0BAFB4), "dex_two":bit3(0x0BAFB4), "cptr_one":bit2(0x0BB228), "cptr_two":bit3(0x0BB228)},
    "Banette":{"dex_one":bit4(0x0BAFB4), "dex_two":bit5(0x0BAFB4), "cptr_one":bit4(0x0BB228), "cptr_two":bit5(0x0BB228)},
    "Rhyhorn":{"dex_one":bit6(0x0BAF77), "dex_two":bit7(0x0BAF77), "cptr_one":bit6(0x0BB1EB), "cptr_two":bit7(0x0BB1EB)},
    "Rhydon":{"dex_one":bit0(0x0BAF78), "dex_two":bit1(0x0BAF78), "cptr_one":bit0(0x0BB1EC), "cptr_two":bit1(0x0BB1EC)},
    "Rhyperior":{"dex_one":bit0(0x0BAFD0), "dex_two":bit1(0x0BAFD0), "cptr_one":bit0(0x0BB244), "cptr_two":bit1(0x0BB244)},
    "Muk":{"dex_one":bit2(0x0BAF72), "dex_two":bit3(0x0BAF72), "cptr_one":bit2(0x0BB1E6), "cptr_two":bit3(0x0BB1E6)},
    "Houndour":{"dex_one":bit0(0x0BAF95), "dex_two":bit1(0x0BAF95), "cptr_one":bit0(0x0BB209), "cptr_two":bit1(0x0BB209)},
    "Houndoom":{"dex_one":bit2(0x0BAF95), "dex_two":bit3(0x0BAF95), "cptr_one":bit2(0x0BB209), "cptr_two":bit3(0x0BB209)},
    "Spinarak":{"dex_one":bit6(0x0BAF85), "dex_two":bit7(0x0BAF85), "cptr_one":bit6(0x0BB1F9), "cptr_two":bit7(0x0BB1F9)},
    "Ariados":{"dex_one":bit0(0x0BAF86), "dex_two":bit1(0x0BAF86), "cptr_one":bit0(0x0BB1FA), "cptr_two":bit1(0x0BB1FA)},
    "Ralts":{"dex_one":bit0(0x0BAFA2), "dex_two":bit1(0x0BAFA2), "cptr_one":bit0(0x0BB216), "cptr_two":bit1(0x0BB216)},
    "Kirlia":{"dex_one":bit2(0x0BAFA2), "dex_two":bit3(0x0BAFA2), "cptr_one":bit2(0x0BB216), "cptr_two":bit3(0x0BB216)},
    "Gardevoir":{"dex_one":bit4(0x0BAFA2), "dex_two":bit5(0x0BAFA2), "cptr_one":bit4(0x0BB216), "cptr_two":bit5(0x0BB216)},
    "Gallade":{"dex_one":bit6(0x0BAFD2), "dex_two":bit7(0x0BAFD2), "cptr_one":bit6(0x0BB246), "cptr_two":bit7(0x0BB246)},
    "Machop":{"dex_one":bit4(0x0BAF6C), "dex_two":bit5(0x0BAF6C), "cptr_one":bit4(0x0BB1E0), "cptr_two":bit5(0x0BB1E0)},
    "Machoke":{"dex_one":bit6(0x0BAF6C), "dex_two":bit7(0x0BAF6C), "cptr_one":bit6(0x0BB1E0), "cptr_two":bit7(0x0BB1E0)},
    "Machamp":{"dex_one":bit0(0x0BAF6D), "dex_two":bit1(0x0BAF6D), "cptr_one":bit0(0x0BB1E1), "cptr_two":bit1(0x0BB1E1)},
    "Mime Jr.":{"dex_one":bit6(0x0BAFC9), "dex_two":bit7(0x0BAFC9), "cptr_one":bit6(0x0BB23D), "cptr_two":bit7(0x0BB23D)},
    "Mr. Mime":{"dex_one":bit4(0x0BAF7A), "dex_two":bit5(0x0BAF7A), "cptr_one":bit4(0x0BB1EE), "cptr_two":bit5(0x0BB1EE)},
    "Drowzee":{"dex_one":bit0(0x0BAF74), "dex_two":bit1(0x0BAF74), "cptr_one":bit0(0x0BB1E8), "cptr_two":bit1(0x0BB1E8)},
    "Hypno":{"dex_one":bit2(0x0BAF74), "dex_two":bit3(0x0BAF74), "cptr_one":bit2(0x0BB1E8), "cptr_two":bit3(0x0BB1E8)},
    "Chimchar":{"dex_one":bit4(0x0BAFBD), "dex_two":bit5(0x0BAFBD), "cptr_one":bit4(0x0BB231), "cptr_two":bit5(0x0BB231)},
    "Monferno":{"dex_one":bit6(0x0BAFBD), "dex_two":bit7(0x0BAFBD), "cptr_one":bit6(0x0BB231), "cptr_two":bit7(0x0BB231)},
    "Infernape":{"dex_one":bit0(0x0BAFBE), "dex_two":bit1(0x0BAFBE), "cptr_one":bit0(0x0BB232), "cptr_two":bit1(0x0BB232)},
    "Vulpix":{"dex_one":bit2(0x0BAF65), "dex_two":bit3(0x0BAF65), "cptr_one":bit2(0x0BB1D9), "cptr_two":bit3(0x0BB1D9)},
    "Ninetales":{"dex_one":bit4(0x0BAF65), "dex_two":bit5(0x0BAF65), "cptr_one":bit4(0x0BB1D9), "cptr_two":bit5(0x0BB1D9)},
    "Skorupi":{"dex_one":bit6(0x0BAFCC), "dex_two":bit7(0x0BAFCC), "cptr_one":bit6(0x0BB240), "cptr_two":bit7(0x0BB240)},
    "Drapion":{"dex_one":bit0(0x0BAFCD), "dex_two":bit1(0x0BAFCD), "cptr_one":bit0(0x0BB241), "cptr_two":bit1(0x0BB241)},
    "Lickilicky":{"dex_one":bit6(0x0BAFCF), "dex_two":bit7(0x0BAFCF), "cptr_one":bit6(0x0BB243), "cptr_two":bit7(0x0BB243)},
    "Ponyta":{"dex_one":bit2(0x0BAF6F), "dex_two":bit3(0x0BAF6F), "cptr_one":bit2(0x0BB1E3), "cptr_two":bit3(0x0BB1E3)},
    "Rapidash":{"dex_one":bit4(0x0BAF6F), "dex_two":bit5(0x0BAF6F), "cptr_one":bit4(0x0BB1E3), "cptr_two":bit5(0x0BB1E3)},
    "Girafarig":{"dex_one":bit6(0x0BAF8E), "dex_two":bit7(0x0BAF8E), "cptr_one":bit6(0x0BB202), "cptr_two":bit7(0x0BB202)},
    "Tauros":{"dex_one":bit0(0x0BAF7C), "dex_two":bit1(0x0BAF7C), "cptr_one":bit0(0x0BB1F0), "cptr_two":bit1(0x0BB1F0)},
    "Ninjask":{"dex_one":bit6(0x0BAFA4), "dex_two":bit7(0x0BAFA4), "cptr_one":bit6(0x0BB218), "cptr_two":bit7(0x0BB218)},
    "Shieldon":{"dex_one":bit4(0x0BAFC2), "dex_two":bit5(0x0BAFC2), "cptr_one":bit4(0x0BB236), "cptr_two":bit5(0x0BB236)},
    "Bastiodon":{"dex_one":bit6(0x0BAFC2), "dex_two":bit7(0x0BAFC2), "cptr_one":bit6(0x0BB236), "cptr_two":bit7(0x0BB236)},
    "Abra":{"dex_one":bit6(0x0BAF6B), "dex_two":bit7(0x0BAF6B), "cptr_one":bit6(0x0BB1DF), "cptr_two":bit7(0x0BB1DF)},
    "Alakazam":{"dex_one":bit2(0x0BAF6C), "dex_two":bit3(0x0BAF6C), "cptr_one":bit2(0x0BB1E0), "cptr_two":bit3(0x0BB1E0)},
    "Murkrow":{"dex_one":bit4(0x0BAF8D), "dex_two":bit5(0x0BAF8D), "cptr_one":bit4(0x0BB201), "cptr_two":bit5(0x0BB201)},
    "Honchkrow":{"dex_one":bit4(0x0BAFC7), "dex_two":bit5(0x0BAFC7), "cptr_one":bit4(0x0BB23B), "cptr_two":bit5(0x0BB23B)},
    "Koffing":{"dex_one":bit2(0x0BAF77), "dex_two":bit3(0x0BAF77), "cptr_one":bit2(0x0BB1EB), "cptr_two":bit3(0x0BB1EB)},
    "Weezing":{"dex_one":bit4(0x0BAF77), "dex_two":bit5(0x0BAF77), "cptr_one":bit4(0x0BB1EB), "cptr_two":bit5(0x0BB1EB)},
    "Skarmory":{"dex_one":bit6(0x0BAF94), "dex_two":bit7(0x0BAF94), "cptr_one":bit6(0x0BB208), "cptr_two":bit7(0x0BB208)},
    "Duskull":{"dex_one":bit6(0x0BAFB4), "dex_two":bit7(0x0BAFB4), "cptr_one":bit6(0x0BB228), "cptr_two":bit7(0x0BB228)},
    "Dusclops":{"dex_one":bit0(0x0BAFB5), "dex_two":bit1(0x0BAFB5), "cptr_one":bit0(0x0BB229), "cptr_two":bit1(0x0BB229)},
    "Dusknoir":{"dex_one":bit2(0x0BAFD3), "dex_two":bit3(0x0BAFD3), "cptr_one":bit2(0x0BB247), "cptr_two":bit3(0x0BB247)},
    "Sableye":{"dex_one":bit4(0x0BAFA7), "dex_two":bit5(0x0BAFA7), "cptr_one":bit4(0x0BB21B), "cptr_two":bit5(0x0BB21B)},
    "Sandshrew":{"dex_one":bit6(0x0BAF62), "dex_two":bit7(0x0BAF62), "cptr_one":bit6(0x0BB1D6), "cptr_two":bit7(0x0BB1D6)},
    "Sandslash":{"dex_one":bit0(0x0BAF63), "dex_two":bit1(0x0BAF63), "cptr_one":bit0(0x0BB1D7), "cptr_two":bit1(0x0BB1D7)},
    "Spiritomb":{"dex_one":bit4(0x0BAFCA), "dex_two":bit5(0x0BAFCA), "cptr_one":bit4(0x0BB23E), "cptr_two":bit5(0x0BB23E)},
    "Spheal":{"dex_one":bit6(0x0BAFB6), "dex_two":bit7(0x0BAFB6), "cptr_one":bit6(0x0BB22A), "cptr_two":bit7(0x0BB22A)},
    "Sealeo":{"dex_one":bit0(0x0BAFB7), "dex_two":bit1(0x0BAFB7), "cptr_one":bit0(0x0BB22B), "cptr_two":bit1(0x0BB22B)},
    "Walrein":{"dex_one":bit2(0x0BAFB7), "dex_two":bit3(0x0BAFB7), "cptr_one":bit2(0x0BB22B), "cptr_two":bit3(0x0BB22B)},
    "Swinub":{"dex_one":bit0(0x0BAF93), "dex_two":bit1(0x0BAF93), "cptr_one":bit0(0x0BB207), "cptr_two":bit1(0x0BB207)},
    "Piloswine":{"dex_one":bit2(0x0BAF93), "dex_two":bit3(0x0BAF93), "cptr_one":bit2(0x0BB207), "cptr_two":bit3(0x0BB207)},
    "Mamoswine":{"dex_one":bit2(0x0BAFD2), "dex_two":bit3(0x0BAFD2), "cptr_one":bit2(0x0BB246), "cptr_two":bit3(0x0BB246)},
    "Jigglypuff":{"dex_one":bit6(0x0BAF65), "dex_two":bit7(0x0BAF65), "cptr_one":bit6(0x0BB1D9), "cptr_two":bit7(0x0BB1D9)},
    "Wigglytuff":{"dex_one":bit0(0x0BAF66), "dex_two":bit1(0x0BAF66), "cptr_one":bit0(0x0BB1DA), "cptr_two":bit1(0x0BB1DA)},
    "Chingling":{"dex_one":bit2(0x0BAFC8), "dex_two":bit3(0x0BAFC8), "cptr_one":bit2(0x0BB23C), "cptr_two":bit3(0x0BB23C)},
    "Piplup":{"dex_one":bit2(0x0BAFBE), "dex_two":bit3(0x0BAFBE), "cptr_one":bit2(0x0BB232), "cptr_two":bit3(0x0BB232)},
    "Prinplup":{"dex_one":bit4(0x0BAFBE), "dex_two":bit5(0x0BAFBE), "cptr_one":bit4(0x0BB232), "cptr_two":bit5(0x0BB232)},
    "Empoleon":{"dex_one":bit6(0x0BAFBE), "dex_two":bit7(0x0BAFBE), "cptr_one":bit6(0x0BB232), "cptr_two":bit7(0x0BB232)},
    "Delibird":{"dex_one":bit2(0x0BAF94), "dex_two":bit3(0x0BAF94), "cptr_one":bit2(0x0BB208), "cptr_two":bit3(0x0BB208)},
    "Jynx":{"dex_one":bit0(0x0BAF7B), "dex_two":bit1(0x0BAF7B), "cptr_one":bit0(0x0BB1EF), "cptr_two":bit1(0x0BB1EF)},
    "Snover":{"dex_one":bit6(0x0BAFCE), "dex_two":bit7(0x0BAFCE), "cptr_one":bit6(0x0BB242), "cptr_two":bit7(0x0BB242)},
    "Abomasnow":{"dex_one":bit0(0x0BAFCF), "dex_two":bit1(0x0BAFCF), "cptr_one":bit0(0x0BB243), "cptr_two":bit1(0x0BB243)},
    "Snorunt":{"dex_one":bit2(0x0BAFB6), "dex_two":bit3(0x0BAFB6), "cptr_one":bit2(0x0BB22A), "cptr_two":bit3(0x0BB22A)},
    "Glalie":{"dex_one":bit4(0x0BAFB6), "dex_two":bit5(0x0BAFB6), "cptr_one":bit4(0x0BB22A), "cptr_two":bit5(0x0BB22A)},
    "Froslass":{"dex_one":bit4(0x0BAFD3), "dex_two":bit5(0x0BAFD3), "cptr_one":bit4(0x0BB247), "cptr_two":bit5(0x0BB247)},
    "Scyther":{"dex_one":bit6(0x0BAF7A), "dex_two":bit7(0x0BAF7A), "cptr_one":bit6(0x0BB1EE), "cptr_two":bit7(0x0BB1EE)},
    "Scizor":{"dex_one":bit0(0x0BAF91), "dex_two":bit1(0x0BAF91), "cptr_one":bit0(0x0BB205), "cptr_two":bit1(0x0BB205)},
    "Dratini":{"dex_one":bit6(0x0BAF80), "dex_two":bit7(0x0BAF80), "cptr_one":bit6(0x0BB1F4), "cptr_two":bit7(0x0BB1F4)},
    "Dragonair":{"dex_one":bit0(0x0BAF81), "dex_two":bit1(0x0BAF81), "cptr_one":bit0(0x0BB1F5), "cptr_two":bit1(0x0BB1F5)},
    "Misdreavus":{"dex_one":bit0(0x0BAF8E), "dex_two":bit1(0x0BAF8E), "cptr_one":bit0(0x0BB202), "cptr_two":bit1(0x0BB202)},
    "Mismagius":{"dex_one":bit2(0x0BAFC7), "dex_two":bit3(0x0BAFC7), "cptr_one":bit2(0x0BB23B), "cptr_two":bit3(0x0BB23B)},
    "Riolu":{"dex_one":bit6(0x0BAFCB), "dex_two":bit7(0x0BAFCB), "cptr_one":bit6(0x0BB23F), "cptr_two":bit7(0x0BB23F)},
    "Lucario":{"dex_one":bit0(0x0BAFCC), "dex_two":bit1(0x0BAFCC), "cptr_one":bit0(0x0BB240), "cptr_two":bit1(0x0BB240)},
    "Torkoal":{"dex_one":bit0(0x0BAFAD), "dex_two":bit1(0x0BAFAD), "cptr_one":bit0(0x0BB221), "cptr_two":bit1(0x0BB221)},
    "Bagon":{"dex_one":bit6(0x0BAFB8), "dex_two":bit7(0x0BAFB8), "cptr_one":bit6(0x0BB22C), "cptr_two":bit7(0x0BB22C)},
    "Shelgon":{"dex_one":bit0(0x0BAFB9), "dex_two":bit1(0x0BAFB9), "cptr_one":bit0(0x0BB22D), "cptr_two":bit1(0x0BB22D)},
    "Salamence":{"dex_one":bit2(0x0BAFB9), "dex_two":bit3(0x0BAFB9), "cptr_one":bit2(0x0BB22D), "cptr_two":bit3(0x0BB22D)},
    "Heatran":{"dex_one":bit2(0x0BAFD5), "dex_two":bit3(0x0BAFD5), "cptr_one":bit2(0x0BB249), "cptr_two":bit3(0x0BB249)},
    "Horsea":{"dex_one":bit0(0x0BAF79), "dex_two":bit1(0x0BAF79), "cptr_one":bit0(0x0BB1ED), "cptr_two":bit1(0x0BB1ED)},
    "Seadra":{"dex_one":bit2(0x0BAF79), "dex_two":bit3(0x0BAF79), "cptr_one":bit2(0x0BB1ED), "cptr_two":bit3(0x0BB1ED)},
    "Kingdra":{"dex_one":bit4(0x0BAF95), "dex_two":bit5(0x0BAF95), "cptr_one":bit4(0x0BB209), "cptr_two":bit5(0x0BB209)},
    "Huntail":{"dex_one":bit6(0x0BAFB7), "dex_two":bit7(0x0BAFB7), "cptr_one":bit6(0x0BB22B), "cptr_two":bit7(0x0BB22B)},
    "Gorebyss":{"dex_one":bit0(0x0BAFB8), "dex_two":bit1(0x0BAFB8), "cptr_one":bit0(0x0BB22C), "cptr_two":bit1(0x0BB22C)},
    "Tentacruel":{"dex_one":bit2(0x0BAF6E), "dex_two":bit3(0x0BAF6E), "cptr_one":bit2(0x0BB1E2), "cptr_two":bit3(0x0BB1E2)},
    "Omanyte":{"dex_one":bit4(0x0BAF7E), "dex_two":bit5(0x0BAF7E), "cptr_one":bit4(0x0BB1F2), "cptr_two":bit5(0x0BB1F2)},
    "Omastar":{"dex_one":bit6(0x0BAF7E), "dex_two":bit7(0x0BAF7E), "cptr_one":bit6(0x0BB1F2), "cptr_two":bit7(0x0BB1F2)},
    "Wailmer":{"dex_one":bit0(0x0BAFAC), "dex_two":bit1(0x0BAFAC), "cptr_one":bit0(0x0BB220), "cptr_two":bit1(0x0BB220)},
    "Cacnea":{"dex_one":bit6(0x0BAFAE), "dex_two":bit7(0x0BAFAE), "cptr_one":bit6(0x0BB222), "cptr_two":bit7(0x0BB222)},
    "Cacturne":{"dex_one":bit0(0x0BAFAF), "dex_two":bit1(0x0BAFAF), "cptr_one":bit0(0x0BB223), "cptr_two":bit1(0x0BB223)},
    "Mothim":{"dex_one":bit4(0x0BAFC3), "dex_two":bit5(0x0BAFC3), "cptr_one":bit4(0x0BB237), "cptr_two":bit5(0x0BB237)},
    "Victreebel":{"dex_one":bit6(0x0BAF6D), "dex_two":bit7(0x0BAF6D), "cptr_one":bit6(0x0BB1E1), "cptr_two":bit7(0x0BB1E1)},
    "Sceptile":{"dex_one":bit4(0x0BAF9B), "dex_two":bit5(0x0BAF9B), "cptr_one":bit4(0x0BB20F), "cptr_two":bit5(0x0BB20F)},
    "Sneasel":{"dex_one":bit6(0x0BAF91), "dex_two":bit7(0x0BAF91), "cptr_one":bit6(0x0BB205), "cptr_two":bit7(0x0BB205)},
    "Weavile":{"dex_one":bit2(0x0BAFCF), "dex_two":bit3(0x0BAFCF), "cptr_one":bit2(0x0BB243), "cptr_two":bit3(0x0BB243)},
    "Hippopotas":{"dex_one":bit2(0x0BAFCC), "dex_two":bit3(0x0BAFCC), "cptr_one":bit2(0x0BB240), "cptr_two":bit3(0x0BB240)},
    "Hippowdon":{"dex_one":bit4(0x0BAFCC), "dex_two":bit5(0x0BAFCC), "cptr_one":bit4(0x0BB240), "cptr_two":bit5(0x0BB240)},
    "Bronzor":{"dex_one":bit0(0x0BAFC9), "dex_two":bit1(0x0BAFC9), "cptr_one":bit0(0x0BB23D), "cptr_two":bit1(0x0BB23D)},
    "Bronzong":{"dex_one":bit2(0x0BAFC9), "dex_two":bit3(0x0BAFC9), "cptr_one":bit2(0x0BB23D), "cptr_two":bit3(0x0BB23D)},
    "Claydol":{"dex_one":bit0(0x0BAFB2), "dex_two":bit1(0x0BAFB2), "cptr_one":bit0(0x0BB226), "cptr_two":bit1(0x0BB226)},
    "Gible":{"dex_one":bit6(0x0BAFCA), "dex_two":bit7(0x0BAFCA), "cptr_one":bit6(0x0BB23E), "cptr_two":bit7(0x0BB23E)},
    "Gabite":{"dex_one":bit0(0x0BAFCB), "dex_two":bit1(0x0BAFCB), "cptr_one":bit0(0x0BB23F), "cptr_two":bit1(0x0BB23F)},
    "Garchomp":{"dex_one":bit2(0x0BAFCB), "dex_two":bit3(0x0BAFCB), "cptr_one":bit2(0x0BB23F), "cptr_two":bit3(0x0BB23F)},
    "Cresselia":{"dex_one":bit0(0x0BAFD6), "dex_two":bit1(0x0BAFD6), "cptr_one":bit0(0x0BB24A), "cptr_two":bit1(0x0BB24A)},
    "Blaziken":{"dex_one":bit2(0x0BAF9C), "dex_two":bit3(0x0BAF9C), "cptr_one":bit2(0x0BB210), "cptr_two":bit3(0x0BB210)},
    "Absol":{"dex_one":bit6(0x0BAFB5), "dex_two":bit7(0x0BAFB5), "cptr_one":bit6(0x0BB229), "cptr_two":bit7(0x0BB229)},
    "Darkrai":{"dex_one":bit6(0x0BAFD6), "dex_two":bit7(0x0BAFD6), "cptr_one":bit6(0x0BB24A), "cptr_two":bit7(0x0BB24A)},
    "Aerodactyl":{"dex_one":bit4(0x0BAF7F), "dex_two":bit5(0x0BAF7F), "cptr_one":bit4(0x0BB1F3), "cptr_two":bit5(0x0BB1F3)},
    "Flygon":{"dex_one":bit4(0x0BAFAE), "dex_two":bit5(0x0BAFAE), "cptr_one":bit4(0x0BB222), "cptr_two":bit5(0x0BB222)},
    "Altaria":{"dex_one":bit4(0x0BAFAF), "dex_two":bit5(0x0BAFAF), "cptr_one":bit4(0x0BB223), "cptr_two":bit5(0x0BB223)},
    "Togekiss":{"dex_one":bit0(0x0BAFD1), "dex_two":bit1(0x0BAFD1), "cptr_one":bit0(0x0BB245), "cptr_two":bit1(0x0BB245)},
    "Porygon-Z":{"dex_one":bit4(0x0BAFD2), "dex_two":bit5(0x0BAFD2), "cptr_one":bit4(0x0BB246), "cptr_two":bit5(0x0BB246)},
    "Celebi":{"dex_one":bit6(0x0BAF9A), "dex_two":bit7(0x0BAF9A), "cptr_one":bit6(0x0BB20E), "cptr_two":bit7(0x0BB20E)},
    "Regirock":{"dex_one":bit2(0x0BAFBA), "dex_two":bit3(0x0BAFBA), "cptr_one":bit2(0x0BB22E), "cptr_two":bit3(0x0BB22E)},
    "Regice":{"dex_one":bit4(0x0BAFBA), "dex_two":bit5(0x0BAFBA), "cptr_one":bit4(0x0BB22E), "cptr_two":bit5(0x0BB22E)},
    "Registeel":{"dex_one":bit6(0x0BAFBA), "dex_two":bit7(0x0BAFBA), "cptr_one":bit6(0x0BB22E), "cptr_two":bit7(0x0BB22E)},
    "Regigigas":{"dex_one":bit4(0x0BAFD5), "dex_two":bit5(0x0BAFD5), "cptr_one":bit4(0x0BB249), "cptr_two":bit5(0x0BB249)},
    "Dialga":{"dex_one":bit6(0x0BAFD4), "dex_two":bit7(0x0BAFD4), "cptr_one":bit6(0x0BB248), "cptr_two":bit7(0x0BB248)},
    "Palkia":{"dex_one":bit0(0x0BAFD5), "dex_two":bit1(0x0BAFD5), "cptr_one":bit0(0x0BB249), "cptr_two":bit1(0x0BB249)},
    "Shaymin":{"dex_one":bit0(0x0BAFD7), "dex_two":bit1(0x0BAFD7), "cptr_one":bit0(0x0BB24B), "cptr_two":bit1(0x0BB24B)},
}    
// $0BBA78: [32bit] Ranger Record - No. of Steps
//          Caps at 9,999,999
// $0BBA7C: [32bit] Ranger Record - No. of Conversations
// $0BBA80: [32bit] Ranger Record - Targets Checked
// $0BBA84: [32bit] Ranger Record  - No. of Saves
// $0BBA88: [32bit] Ranger Record - No. of Pokemon Rides
// $0BBAC0: Possible Start of Catch Table
// $0BBAD0: [32bit[ Ranger Record - Capture Line Length (ft.)
//          To Get Value , divide by 48
// $0BBAD4: [32bit] Ranger Record - No. of Loops
// $0BBAD8: [16bit] Ranger Record - Pokemon Captured
// $0BBADA: [16bit] Ranger Record - Abandoned Attempts (Fled)
// $0BBADC: [32bit] Ranger Record - Poke Assists Used
// $0BBAF4: [32bit] Ranger Record - Player Time - Hours
// $0BBAF8: [8bit] Ranger Record - Player Time (Minutes)
// $0BBAF9: ??? [8bit] Ranger Record - Play Time (Seconds???)
// $0BBB3C: [16bit] Party Slot 1 - Pokemon ID
// $0BBB54: [16bit] Party Slot 2 - Pokemon ID
// $0BBB6C: [16bit] Party Slot 3 - Pokemon ID
// $0BBB84: [16bit] Party Slot 4 - Pokemon ID
// $0BBB9C: [16bit] Party Slot 5 - Pokemon ID
// $0BBBB4: [16bit] Party Slot 6 - Pokemon ID
// $0BBBCC: [16bit] Party Slot 7 - Pokemon ID
// $0BBBE4: [16bit] Party Slot 8 - Pokemon ID
// $0BBBFC: [16bit] Party Slot 9 - Pokemon ID
// $0BBC14: [16bit] Ocean Party Slot 1 - Pokemon ID
// $0BBC2C: [16bit] Ocean Party Slot 2 - Pokemon ID
// $0BBC44: [16bit] Ocean Party Slot 3 - Pokemon ID
// $10CD88: [8bit] Window Color Option
//          0x00=Gold
//          0x01=Red
//          0x02=Green
//          0x03=Blue
//          0x04=Grey
//          0x06=Pink
//          0x07=Light Pink
//          0x08=Rainbow
// $10CD8C: [8bit] Text Speed Option
//          0x03=Slowest
//          0x02=Medium
//          0x01=Fastest
// $127030: [32bit] 1-Loop Capture Cheat - Set to 0xE3A00000
// $17C074: [Pointer]
//          [24bit + 0x1548] Pointer for Pokémon 1 in Battle (24bit)
//          ---[24bit + 0x188]Progress
// $27784C: [24bit] Pointer - Pokemon Num 1
//          Offset: 0x188 - [16bit] Capture Progress Bar
// $28E93C: Main Damage Counter
// $2A5520: Pokedex Entry ID Number
// $2F510E: Health- In-Battle [16bit]
// $2F5110: Total Health- In Battle [16bit]
// $2FD552: HP Tutorial [16bit]
// $2FD554: Max HP Tutorial [32bit]
// $3FFFAA: Style Tracking
// $3FFFAD: Stylus making contact on screen
//          06 = no contact
//          01 = current contact
//==========START OF CALLS==========
// $0BAFBF: [NBit] Pokemon Bitflags
//          Bit6-7=Bidoof
function game_state() => byte(0x08af58)
//Add in state check to prevent autoflicker on menu! 7-19-2023
function flicker_check() => prev(game_state()) < 3
function save_check() => prev(bit7(0x0bafbf)) == 1 && flicker_check()
function save_check_hits() => never(prev(bit7(0x0bafbf)) == 0)
// $0B32B8: [8bit] Active Mission IsDisplayed Flag
//          0x00=False
//          0x01=True
achievement(
    "Spooky Hide and Seek",
    "Bring all four stylers to the basement, and capture Gastly!",
    id=159870,
    badge="179710",
    points=5,
    trigger=
        save_check() &&        
        pokemon_database["Gastly"]["dex_two"] > prev( pokemon_database["Gastly"]["dex_two"])
)
achievement(
    "Trouble On the Beach",
    "Help soothe the Pokemon on the Beach!",
    id=159881,
    badge="179718",
    points=5,
    trigger=        
        save_check() && 
        (always_false() ||          
            pokemon_database["Starly"]["dex_two"] > prev( pokemon_database["Starly"]["dex_two"]) ||            
            pokemon_database["Pachirisu"]["dex_two"] > prev( pokemon_database["Pachirisu"]["dex_two"]) ||
            pokemon_database["Munchlax"]["dex_two"] > prev( pokemon_database["Munchlax"]["dex_two"])            
         )
)            
function mission_isDisplayed() => byte(0x0b32b8)
// $0B32B9: [8bit] Ongoing Quest IsShown Flag
//          0x00=False
//          0x01=True
// $0B32BA: [8bit] Active Mission ID
//          0x1=Deliver Vien Tribune!
//          0x2=Investigate the Marine Cave!
//          0x3=Fight the Forest Fire!
//          0x4=Destroy the Strange Machines !
//          0x5=Recover a Key from Sharpedo!
//          0x6=Seek the Origin of the Quake!
//          0x7=Teach at Ranger School!
//          0x8=Look for Missing Barlow!
//          0x9=Support Sven at the Ruins!
//          0xa=Get the Blue Gem!
//          0xb=Get the Red Gem!
//          0xc=Rescue Wailord!
//          0xd=Reveal the Hideout's Secrets!
//          0xe=Get the Yellow Gem!
//          0xf=Protect Ranger Union HQ!
//          0x11=Execute Operation Brighton!
//          0x46=DLC - Recover the Manaphy Egg!
//          0x47=DLC - Rescue Kidnapped Riolu!
//          0x48=DLC - Liberate the Tower!
//          0x49=DLC - Dialga in Hia Valley?
//          0x4a=DLC - Palkia in Haruba Desert?
//          0x4b=DLC - For the Bride & Shaymin
function active_mission() => byte(0x0b32ba)
mission_list = {
    0x1:{"Name":"Newspaper Delivery!", "Desc":"Complete the story mission Deliver Vien Tribune!", "PrevID":0, "Points":10, "ID":159479, "Badge":"179575"},
    0x2:{"Name":"Explore the Marine Cave!", "Desc":"Complete the story mission Investigate the Marine Cave", "PrevID":1, "Points":10, "ID":159480, "Badge":"179576"},
    0x3:{"Name":"Vien Forest Fire Mayhem", "Desc":"Complete the story mission Fight the Forest Fire!", "PrevID":2, "Points":10, "ID":159481, "Badge":"179577"},
    0x4:{"Name":"Gigaremo Confusion", "Desc":"Complete the story mission Destroy the Strange Machines!", "PrevID":3, "Points":10, "ID":159482, "Badge":"179578"},
    0x5:{"Name":"Chasing Sharpedo", "Desc":"Complete the story mission Recover a Key from Sharpedo!", "PrevID":4, "Points":10, "ID":159483, "Badge":"179579"},
    0x6:{"Name":"Earthquaking Confusion!", "Desc":"Complete the story mission Seek the Origin of the Quake!", "PrevID":5, "Points":10, "ID":159484, "Badge":"179580"},
    0x7:{"Name":"The Student is Now the Teacher", "Desc":"Complete the story mission Teach at Ranger School!", "PrevID":6, "Points":10, "ID":159485, "Badge":"179581"},
    0x8:{"Name":"Where's Barlow?", "Desc":"Complete the story mission Look for Missing Barlow!", "PrevID":7, "Points":10, "ID":159486, "Badge":"179582"},
    0x9:{"Name":"Backup for Sven", "Desc":"Complete the story mission Support Sven at the Ruins!", "PrevID":8, "Points":10, "ID":159487, "Badge":"179583"},
    0xa:{"Name":"Blue Gem Snatcher", "Desc":"Complete the story mission Get the Blue Gem!", "PrevID":9, "Points":10, "ID":159488, "Badge":"179584"},
    0xb:{"Name":"Red Gem Grabber", "Desc":"Complete the story mission Get the Red Gem!", "PrevID":0xa, "Points":10, "ID":159489, "Badge":"179585"},
    0xc:{"Name":"Whale Rescuer", "Desc":"Complete the story mission Rescue Wailord!", "PrevID":0xb, "Points":10, "ID":159490, "Badge":"179586"},
    0xd:{"Name":"Mysterious Hideout", "Desc":"Complete the story mission Reveal the Hideout's Secrets!", "PrevID":0xc, "Points":10, "ID":159491, "Badge":"179587"},
    0xe:{"Name":"Yellow Gem Protector", "Desc":"Complete the story mission Get the Yellow Gem!", "PrevID":0xd, "Points":10, "ID":159492, "Badge":"179588"},
    0xf:{"Name":"Protect Home Base", "Desc":"Complete the story mission Protect Ranger Union HQ!", "PrevID":0xe, "Points":10, "ID":159493, "Badge":"179589"},
    0x11:{"Name":"The Light of the World", "Desc":"Complete the story mission Execute Operation Brighton!", "PrevID":0xf, "Points":25, "ID":159494, "Badge":"179590"}
}
// $0B32BB: [8bit] Active Quest ID
// $0B32BC: [8bit] Number of Missions Cleared
//           DLC: Utilize Active Mission Flag
function mission_clear(ID) =>
        active_mission() == ID &&
        mission_isDisplayed() < prev(mission_isDisplayed()) &&
        mission_isDisplayed() == 0
        
for mission in mission_list{
    achievement(
        mission_list[mission]["Name"],
        mission_list[mission]["Desc"],
        id=mission_list[mission]["ID"],
        badge=mission_list[mission]["Badge"],
        points=mission_list[mission]["Points"],
        trigger=
            save_check() &&
            mission_clear(mission)          
    )
}
//=====SIDE-QUESTS=====
quest_list = {
    0:{"Name":"Calm Down Miltank", "Desc":"Help the Vientown farmer calm down Miltank!", "ID":159495, "Badge":"179591", "Points":5},
    1:{"Name":"Breeze Hill Sign Recovery", "Desc":"Clear the boulder on the beach near Vientown!", "ID":159496, "Badge":"179592", "Points":5},
    2:{"Name":"Is Combee Okay?", "Desc":"Capture a Combee for the old lady in Vientown!", "ID":159497, "Badge":"179593", "Points":5},
    3:{"Name":"Clear the Crates!", "Desc":"Practice your target clear, and destroy some creates!", "ID":159498, "Badge":"179594", "Points":5},
    4:{"Name":"The Boy Who Cried Lumineon", "Desc":"Bring a fisherman a Lumineon", "ID":159499, "Badge":"179595", "Points":5},
    5:{"Name":"Nosepass! Must Have Nosepass", "Desc":"Bring a man a pokemon with a big nose", "ID":159500, "Badge":"179596", "Points":5},
    6:{"Name":"Who Ate My Lunch?", "Desc":"Capture an Ambipom that ran off!", "ID":159501, "Badge":"179597", "Points":5},
    7:{"Name":"Eevee for Marital Bliss", "Desc":"Bring a man in Pueltown an Eevee", "ID":159502, "Badge":"179598", "Points":5},
    8:{"Name":"Oddish Research", "Desc":"Help a man see an Oddish", "ID":159503, "Badge":"179599", "Points":5},
    9:{"Name":"Light the Leaves", "Desc":"Make some leaves burn", "ID":159504, "Badge":"179601", "Points":5},
    10:{"Name":"Clear Some Fallen Logs", "Desc":"Clear some fallen trees in Vien Forest", "ID":159505, "Badge":"179600", "Points":5},
    11:{"Name":"Cherrim, Cherrim, Come to Us", "Desc":"Sing a song, and bring a Cherrim to a young lady", "ID":159506, "Badge":"179602", "Points":5},
    12:{"Name":"Team Dim Sun's Appetite", "Desc":"Rescue a girl stuck in Volcano Cave", "ID":159507, "Badge":"179603", "Points":5},
    13:{"Name":"That Smell of Muk", "Desc":"Strangely, bring a Muk to a man that requested one", "ID":159508, "Badge":"179604", "Points":5},
    14:{"Name":"Dim...Sun...Come Back...", "Desc":"Bring a girl two Murkrow", "ID":159509, "Badge":"179605", "Points":5},
    15:{"Name":"Apologies to Vespiquen", "Desc":"Battle a Vespiquen and two Combee on Union Road to clear this mission", "ID":159510, "Badge":"179606", "Points":5},
    16:{"Name":"Lonely Chingling", "Desc":"Bring Chingling a companion in Pueltown", "ID":159511, "Badge":"179607", "Points":5},
    17:{"Name":"Abomasnow Research", "Desc":"Capture an Abomasnow near Shiver Camp for research", "ID":159512, "Badge":"179608", "Points":5},
    18:{"Name":"Melt The Ice", "Desc":"Melt the potential ice falls in Crysta Lake", "ID":159513, "Badge":"179609", "Points":5},
    19:{"Name":"Drifblim's Moving Service", "Desc":"Capture three Drifblim for an old couple", "ID":159514, "Badge":"179610", "Points":5},
    20:{"Name":"Secure The Hidden Harbor", "Desc":"Extinguish some fires in a cave in Boyleland", "ID":159515, "Badge":"179611", "Points":5},
    21:{"Name":"Thaw The Frozen Door", "Desc":"Clear the ice fall in front of a Shiver Camp house", "ID":159516, "Badge":"179612", "Points":5},
    22:{"Name":"My Precious Fishing Rod", "Desc":"Find a lost item in the Sea of Wailord", "ID":159517, "Badge":"179613", "Points":5},
    23:{"Name":"Unidentified Fleeing Omastar", "Desc":"Capture an Omastar and bring it to the fisherman in Pueltown", "ID":159518, "Badge":"179614", "Points":5},
    24:{"Name":"Cacturne Research", "Desc":"Capture a Cacturne for a scientist on Haruba Village", "ID":159519, "Badge":"179615", "Points":5},
    25:{"Name":"Smelly Skuntank and Weezing", "Desc":"Bring an archeologist two stinky pokemon in Haruba Village", "ID":159520, "Badge":"179616", "Points":5},
    26:{"Name":"Capture Gigaremo Units", "Desc":"Face two Claydols in Hippowdon Temple", "ID":159521, "Badge":"179617", "Points":5},
    27:{"Name":"Elaine's Favorite Dragon", "Desc":"Hunt down a Dragonair and bring it to Elaine in Vientown", "ID":159522, "Badge":"179618", "Points":5},
    28:{"Name":"Murph's Ranger Contest", "Desc":"Bring all seven Eevee forms to a man in the Ranger Union", "ID":159523, "Badge":"179619", "Points":10}, //10 points
    29:{"Name":"Roserade Red, Roserade Blue", "Desc":"Capture a Roserade and bring it to the girl in the Ranger Union", "ID":159524, "Badge":"179620", "Points":5},
    30:{"Name":"Charge Up The Trio!", "Desc":"Bring three fully evolved electric Pokemon to the scientist at the Ranger Union", "ID":159525, "Badge":"179621", "Points":5},
    31:{"Name":"Access the Ice Castle", "Desc":"Clear the ice blocks outside of Almia Castle", "ID":159526, "Badge":"179622", "Points":5},
    32:{"Name":"Mom's Best Recipe", "Desc":"Check the Refrigerator for your mom", "ID":159527, "Badge":"179623", "Points":2}, //2 points
    33:{"Name":"White Pokemon For Peace", "Desc":"Capture a fully evolved egg pokemon and bring it to Altru Square", "ID":159528, "Badge":"179624", "Points":5},
    34:{"Name":"Please Save Cranidos", "Desc":"Gain a new friend to join your party", "ID":159529, "Badge":"179625", "Points":5},
    35:{"Name":"Please Save Shieldon", "Desc":"Gain another friend to join your party", "ID":159530, "Badge":"179626", "Points":5},
    36:{"Name":"Please Save Chimchar", "Desc":"Save Chimchar, and have it join your party", "ID":159531, "Badge":"179627", "Points":5},
    37:{"Name":"Mischievous Sneasel", "Desc":"Capture the pokemon causing havoc in Almia Castle", "ID":159532, "Badge":"179628", "Points":5},
    38:{"Name":"Snover's Mysterious Presence", "Desc":"Rescue Snover stuck on a cliff!", "ID":159533, "Badge":"179629", "Points":5},
    39:{"Name":"Mischievous Misdreavus", "Desc":"Battle Misdreavus near the entrance to Chroma Ruins", "ID":159534, "Badge":"179630", "Points":5},    
    43:{"Name":"Is Machop Ok?", "Desc":"Face Machop and capture it!", "ID":159536, "Badge":"179632", "Points":5},
    44:{"Name":"Save Piplup!", "Desc":"Rescue Piplup and have it join your party", "ID":159537, "Badge":"179633", "Points":5},
    45:{"Name":"Rescue Turtwig", "Desc":"Challenge Turtwig near Marine Cave", "ID":159538, "Badge":"179634", "Points":5},
    46:{"Name":"Hippowdon's Nose?", "Desc":"Capture Hippopotas at the top of Hippowdon Temple", "ID":159539, "Badge":"179635", "Points":5},
    47:{"Name":"Pleaful Pelipper", "Desc":"Follow a Pelipper through the Volcano, and capture Gible", "ID":159540, "Badge":"179636", "Points":5},
    48:{"Name":"Under the Bridge", "Desc":"Meet some people at a Bridge", "ID":159541, "Badge":"179637", "Points":2}, //2 points
    49:{"Name":"Strange Crates On the Shore", "Desc":"Crush a box on a beach", "ID":159542, "Badge":"179638", "Points":2}, //2 points
    50:{"Name":"Talk to Your Mom", "Desc":"Deliver a message for a friend in Pueltown", "ID":159543, "Badge":"179639", "Points":3}, //3 points
    51:{"Name":"What Reporter Hans Forgot", "Desc":"Tell a reporter about what Altru Tower looks like", "ID":159544, "Badge":"179640", "Points":3}, //3 pt
    52:{"Name":"Bring Back The Oasis", "Desc":"Fill up the lake in Haruba Village with a Blastoise", "ID":159545, "Badge":"179641", "Points":5},
    53:{"Name":"Wish For Vien Forest", "Desc":"Find a Pokemon that could heal the Vien Forest from the fire", "ID":159546, "Badge":"179642", "Points":5},
    54:{"Name":"The Secret of Three", "Desc":"Move a statue and find a diary", "ID":159547, "Badge":"179643", "Points":5},
    55:{"Name":"Snow on the Island", "Desc":"Make it snow in Boyleland!", "ID":159548, "Badge":"179644", "Points":5},
    56:{"Name":"For Little Tim", "Desc":"Bring the farmhouse lady a Slakoth", "ID":159549, "Badge":"179645", "Points":5},
    57:{"Name":"Murph's Disappearing Act", "Desc":"Locate the grandson in Almia Castle", "ID":159550, "Badge":"179646", "Points":5},
    58:{"Name":"Staraptor High In The Sky", "Desc":"Bring the girl in the Ranger Union six Staraptor", "ID":159551, "Badge":"179647", "Points":5},
    59:{"Name":"The Gift of Music for Isaac", "Desc":"Capture four musical Pokemon for the girl to perform with!", "ID":159552, "Badge":"179648", "Points":5},
    60:{"Name":"Ponte's Path", "Desc":"Bring a Team Dim Sun member a Probopass", "ID":159553, "Badge":"179649", "Points":5}    
}
quest_table_start = 0x0B32CD
function sidequest_progression(address) =>
    save_check() &&
            bit4(address) == 1 &&
            prev(bit0(address)) == 1 &&
            bit1(address) == 1
//First 40 quests. 
for quest in range(0, 39){
    achievement(
        quest_list[quest]["Name"],
        quest_list[quest]["Desc"],
        id=quest_list[quest]["ID"],
        badge=quest_list[quest]["Badge"],
        points=quest_list[quest]["Points"],
        trigger=
            sidequest_progression(quest_table_start + quest)
    )    
}
//Calls for starter specific quests.
achievement(
    "Partner Mayhem",
    "Recruit Munchlax, Starly, and Pachirisu",
    id=159535,
    badge="179631",
    points=5,
    trigger=
        save_check() &&
        prev(pokemon_database["Munchlax"]["dex_two"]) +  prev(pokemon_database["Starly"]["dex_two"]) +  prev(pokemon_database["Pachirisu"]["dex_two"])  < 3 &&
        measured(pokemon_database["Munchlax"]["dex_two"] + pokemon_database["Starly"]["dex_two"] + pokemon_database["Pachirisu"]["dex_two"] == 3)        
)
//Finish quests 43-60. 
for quest in range(43, 60){
    achievement(
        quest_list[quest]["Name"],
        quest_list[quest]["Desc"],
        id=quest_list[quest]["ID"],
        badge=quest_list[quest]["Badge"],
        points=quest_list[quest]["Points"],
        trigger=
            sidequest_progression(quest_table_start + quest)
    )
}
//=====DLC MISSIONS=====
achievement(
    "Tracking Down an Egg!",
    "Find Happiny and recover Manaphy's Egg!",
    id=159554,
    badge="179305",
    points=5,
    trigger=
        save_check() &&
        mission_clear(0x46)               
)
achievement(
    "Riolu Rescue!",
    "Rescue Riolu in a Special Episode!",
    id=159555,
    badge="179306",
    points=5,
    trigger=
        save_check() &&
        mission_clear(0x47)
        
)
achievement(
    "Team...Debonair?",
    "Help Darkrai liberate Altru Tower!",
    id=159556,
    badge="179307",
    points=10,
    trigger=
        save_check() &&
        mission_clear(0x48)
        
)
achievement(
    "Strange Times With Dialga",
    "Solve the rift of time that took your family!",
    id=159557,
    badge="179308",
    points=10,
    trigger=
        save_check() &&
        mission_clear(0x49)
)
achievement(
    "A Distorted Village",
    "Track down Palkia and restore distorted space in Haruba Village!",
    id=159558,
    badge="179309",
    points=10,
    trigger=
        save_check() &&
        mission_clear(0x4a)  
)
achievement(
    "Vows and Bouquets",
    "Capture Shaymin at the wedding before Team Dim Sun does!",
    id=159559,
    badge="179310",
    points=10,
    trigger=
        save_check() &&
        mission_clear(0x4b)
)
//=====CAPTURE ARENA=====
// $0B32BB: [NBit] Local Event - Capture Arena 1st Floor Door Flags
//          00=Red
//          01=Green
//          Bit1=Floor 1 Room 1 Cleared
//          Bit2=Floor 1 Room 2 Cleared
//          Bit3=Floor 1 Room 3 Cleared
//          Bit4=Floor 1 Room 4 Cleared
//          Bit5=Floor 1 Final Room - Cresselia Door
function cresselia_door() => bit5(0x10cdf4)
function flrtwo_roomone_door() => bit1(0x10cdf8)
function flrtwo_roomtwo_door() => bit2(0x10cdf8)
function flrtwo_roomthree_door() => bit3(0x10cdf8)
function flrtwo_roomfour_door() => bit4(0x10cdf8)
function flrthree_roomone_door() => bit1(0x10cdfc)
function flrthree_roomtwo_door() => bit2(0x10cdfc)
function flrthree_roomthree_area() => bit3(0x10cdfc)
function arena_clear(roomID, doorFlag) =>    
    location() == roomID &&
    doorFlag > prev(doorFlag)

achievement(
    "First Lunar Floor",
    "Complete Floor 1 of the Capture Arena for the first time",
    id=159560,
    badge="179650",
    points=10,
    trigger=
        save_check() &&
        arena_clear(0x182, cresselia_door())  //RoomID 0x82 = Main Room of Floor 1. 
)    
achievement(
    "Gliscor and Yanmega Round Two!",
    "Complete Room 1, Floor 2 of the Capture Arena for the first time",
    id=159561,
    badge="179651",
    points=10,
    trigger=
        save_check() &&
        arena_clear(0x196, flrtwo_roomone_door()) //RoomID 0x96 = Main Room of Floor 2.
)
achievement(
    "Triple Trouble!",
    "Complete Room 2, Floor 2 of the Capture Arena for the first time",
    id=159562,
    badge="179652",
    points=10,
    trigger=
        save_check() &&
        arena_clear(0x196, flrtwo_roomtwo_door())
)
achievement(
    "Eeveelution Mania!",
    "Complete Room 3, Floor 2 of the Capture Arena for the first time",
    id=159563,
    badge="179653",
    points=10,
    trigger=
        save_check() &&
        arena_clear(0x196, flrtwo_roomthree_door())
)
achievement(
    "Clawing Through the Arena",
    "Complete the last room on Floor 2 of the Capture Arena for the first time",
    id=159564,
    badge="179654",
    points=25,
    trigger=
        save_check() &&
        arena_clear(0x196, flrtwo_roomfour_door())
)
achievement(
    "Shocking Fire",
    "Complete Room 1, Floor 3 of the Capture Arena for the first time",
    id=159565,
    badge="179655",
    points=10,
    trigger=
        save_check() &&
        arena_clear(0x1b1, flrthree_roomone_door())
)
achievement(
    "Fourth Generation of Starters",
    "Complete Room 2, Floor 3 of the Capture Arena for the first time",
    id=159566,
    badge="179656",
    points=10,
    trigger=
        save_check() &&
        arena_clear(0x1b1, flrthree_roomtwo_door())
)
achievement(
    "The Final Challenge",
    "Complete the last room and clear the Capture Arena for the first time",
    id=159567,
    badge="179657",
    points=50,
    trigger=
        save_check() &&
        arena_clear(0x1b1, flrthree_roomthree_area())
        
)
//=====ROOM CHALLENGES=====
// $0bbae0: [16bit] On-Screen Timer for Events (Frames)
//          Used at Team Dim Sun Base
function frame_timer() => word(0x0bbae0)
// $0B333C: [16bit] Player x
//          For Volcano Cave:
//          Left Extremity X Coord = 0xd4
//          Right Extremity X Coord = 0x190
function player_x_coord() => word(0x0b333c)
// $0B333E: [16bit] Player Y
//          For Volcano Cave:
//          Y-Coordinate Check = 0x127
function player_y_coord() => word(0x0b333e)
achievement(
    "[m] Dim Sun Speed Run",
    "Reach Team Dim Sun's Cargo Ship in Volcano Cave within 10 seconds or less",
    id=159568,
    badge="179430",
    points=5,
    trigger=
        unless(repeated(0x258, frame_timer() < prev(frame_timer()))) && //Time in Frames: 0x258 = 10 seconds.
        location() == 0x8d && //Volcano Cave - Team Dim Sun Ship        
        player_x_coord() >= 0xd4 && 
        player_x_coord() <= 0x190 &&
        trigger_when(player_y_coord() <= 0x127) &&        
        (always_false() || never(frame_timer() > prev(frame_timer()))) //Reset if timer is reset to 2/3 minutes.
)
achievement(
    "Qwilfish Fun!",
    "Swim through the Qwilfish room in the Sea of Wailord without taking styler damage",
    id=159569,
    badge="179429",
    points=5,
    trigger=            
        never(prev(location()) == 0x101 && location() == 0x102) && //Prevents player from cheesing by passing through tube to get around room.
        never(environment_health() < prev(environment_health())) &&
        once(prev(location()) == 0x101 && location() == 0x105) &&//Set hit from beginning of previous room.
        trigger_when(prev(location()) == 0x105 && location() == 0x102)
)
//=====BOSS S-RANK CHALLENGES=====
function in_swap() => byte(0x08af58) == 0x2
function boss_rank_capture(cptr_one, cptr_two, dex_two) =>
    save_check() &&
    prev(dex_two) == 0 &&
    prev(cptr_one) + prev(cptr_two) != 0 &&
    cptr_one +
    cptr_two == 0 &&
    in_swap()
achievement(
    "Growing Through Capturing",
    "Obtain an S rank capture on Tangrowth on the first encounter",
    id=159570,
    badge="179400",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Tangrowth"]["cptr_one"], 
            pokemon_database["Tangrowth"]["cptr_two"], 
            pokemon_database["Tangrowth"]["dex_two"]
            )    
)   
achievement(
    "Maximum Poison",
    "Obtain a S rank capture on Toxicroak on the first encounter",
    id=159571,
    badge="179401",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Toxicroak"]["cptr_one"], 
            pokemon_database["Toxicroak"]["cptr_two"], 
            pokemon_database["Toxicroak"]["dex_two"]
        )
)
achievement(
    "Rampaging Capture",
    "Obtain a S rank capture on Rampardos on the first encounter",
    id=159572,
    badge="179402",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Rampardos"]["cptr_one"], 
            pokemon_database["Rampardos"]["cptr_two"], 
            pokemon_database["Rampardos"]["dex_two"] 
        )
)
achievement(
    "Hunter J's Bounty",
    "Obtain a S rank capture on Drapion on the first encounter",
    id=159573,
    badge="179403",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Drapion"]["cptr_one"], 
            pokemon_database["Drapion"]["cptr_two"], 
            pokemon_database["Drapion"]["dex_two"] 
        )
)   
achievement(
    "Rest in Spirits",
    "Obtain a S rank capture on Spiritomb on the first encounter",
    id=159574,
    badge="179404",
    points=25,
    trigger=
        boss_rank_capture(
            pokemon_database["Spiritomb"]["cptr_one"], 
            pokemon_database["Spiritomb"]["cptr_two"], 
            pokemon_database["Spiritomb"]["dex_two"] 
        )
)
achievement(
    "Frosty Attitude",
    "Obtain a S rank capture on Froslass on the first encounter",
    id=159575,
    badge="179405",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Froslass"]["cptr_one"], 
            pokemon_database["Froslass"]["cptr_two"], 
            pokemon_database["Froslass"]["dex_two"] 
        )
)
achievement(
    "A Dramatic Fight!",
    "Obtain a S rank capture on Lucario on the first encounter",
    id=159576,
    badge="179406",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Lucario"]["cptr_one"], 
            pokemon_database["Lucario"]["cptr_two"], 
            pokemon_database["Lucario"]["dex_two"] 
        ) 
)
achievement(
    "Super Fire Monkey",
    "Obtain a S rank capture on Infernape on the first encounter",
    id=159577,
    badge="179407",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Infernape"]["cptr_one"], 
            pokemon_database["Infernape"]["cptr_two"], 
            pokemon_database["Infernape"]["dex_two"] 
        )     
)
achievement(
    "Guardian of the Red Gem",
    "Obtain a S rank capture on Heatran on the first encounter",
    id=159578,
    badge="179408",
    points=25,
    trigger=
        boss_rank_capture(
            pokemon_database["Heatran"]["cptr_one"], 
            pokemon_database["Heatran"]["cptr_two"], 
            pokemon_database["Heatran"]["dex_two"] 
        )   
)
achievement(
    "King of the Sea",
    "Obtain a S rank capture on Kingdra on the first encounter",
    id=159579,
    badge="179409",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Kingdra"]["cptr_one"], 
            pokemon_database["Kingdra"]["cptr_two"], 
            pokemon_database["Kingdra"]["dex_two"] 
        )
)
achievement(
    "Slicing Loops",
    "Obtain a S rank capture on Gliscor on the first encounter",
    id=159580,
    badge="179410",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Gliscor"]["cptr_one"], 
            pokemon_database["Gliscor"]["cptr_two"], 
            pokemon_database["Gliscor"]["dex_two"]
        )
)
achievement(
    "A Crescent Moon",
    "Obtain a S rank capture on Cresselia on the first encounter",
    id=159581,
    badge="179411",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Cresselia"]["cptr_one"], 
            pokemon_database["Cresselia"]["cptr_two"], 
            pokemon_database["Cresselia"]["dex_two"]
        )
)
achievement(
    "Magnetic Energy",
    "Obtain a S rank capture on Magnezone on the first encounter",
    id=159582,
    badge="179412",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Magnezone"]["cptr_one"], 
            pokemon_database["Magnezone"]["cptr_two"], 
            pokemon_database["Magnezone"]["dex_two"]
        )    
)
achievement(
    "Electrifying Encounter!",
    "Obtain a S rank capture on Electivire on the first encounter",
    id=159583,
    badge="179413",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Electivire"]["cptr_one"], 
            pokemon_database["Electivire"]["cptr_two"], 
            pokemon_database["Electivire"]["dex_two"]
        )
)
achievement(
    "Chompin' Away at the Browser",
    "Obtain a S rank capture on Garchomp on the first encounter",
    id=159584,
    badge="179414",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Garchomp"]["cptr_one"], 
            pokemon_database["Garchomp"]["cptr_two"], 
            pokemon_database["Garchomp"]["dex_two"]
        )
)
achievement(
    "Rockin' Capture",
    "Obtain a S rank capture on Rhyperior on the first encounter",
    id=159585,
    badge="179415",
    points=10,
    trigger=
        boss_rank_capture(
            pokemon_database["Rhyperior"]["cptr_one"], 
            pokemon_database["Rhyperior"]["cptr_two"], 
            pokemon_database["Rhyperior"]["dex_two"]
        )
)
achievement(
    "Hot Magma",
    "Obtain a S rank capture on Magmortar on the first encounter",
    id=159586,
    badge="179416",
    points=25,
    trigger=
        boss_rank_capture(
            pokemon_database["Magmortar"]["cptr_one"], 
            pokemon_database["Magmortar"]["cptr_two"], 
            pokemon_database["Magmortar"]["dex_two"]
        )
)
achievement(
    "Slashin' Your Loops",
    "Obtain a S rank capture on Gallade on the first encounter",
    id=159587,
    badge="179417",
    points=25,
    trigger=
        boss_rank_capture(
            pokemon_database["Gallade"]["cptr_one"], 
            pokemon_database["Gallade"]["cptr_two"], 
            pokemon_database["Gallade"]["dex_two"]
        )
)
achievement(
    "Trio Trouble",
    "Capture Gallade, Rhyperior, and Magmortar, and target clear the final Circuit Ball!",
    id=159588,
    badge="179418",
    points=10,
    trigger=
        prev(location()) == 0x167 &&
        location() == 0x169
)
achievement(
    "Dusknoir the Explorer",
    "Obtain a S rank capture on Dusknoir on the first encounter",
    id=159589,
    badge="179419",
    points=25,
    trigger=
        boss_rank_capture(
            pokemon_database["Dusknoir"]["cptr_one"], 
            pokemon_database["Dusknoir"]["cptr_two"], 
            pokemon_database["Dusknoir"]["dex_two"]
        )
)

achievement(
    "The Darkest Memories",
    "Obtain a S rank capture on Darkrai",
    id=159590,
    badge="179420",
    points=25,
    trigger=
        save_check() &&
        prev(pokemon_database["Darkrai"]["cptr_one"]) + 
        prev(pokemon_database["Darkrai"]["cptr_two"]) != 0 &&
        pokemon_database["Darkrai"]["cptr_one"] +
        pokemon_database["Darkrai"]["cptr_two"] == 0                
)


achievement(
    "Body of Ice",
    "Obtain a S rank capure on Regice",
    id=159690,
    badge="179425",
    points=10,
    trigger=
        save_check() && 
        flicker_check() &&
        prev(pokemon_database["Regice"]["cptr_one"]) + 
        prev(pokemon_database["Regice"]["cptr_two"]) != 0 &&
        pokemon_database["Regice"]["cptr_one"] +
        pokemon_database["Regice"]["cptr_two"] == 0
)
achievement(
    "Body of Rock",
    "Obtain a S rank capture on Regirock",
    id=159691,
    badge="179426",
    points=10,
    trigger=
        save_check() &&
        flicker_check() &&
        prev(pokemon_database["Regirock"]["cptr_one"]) + 
        prev(pokemon_database["Regirock"]["cptr_two"]) != 0 &&
        pokemon_database["Regirock"]["cptr_one"] +
        pokemon_database["Regirock"]["cptr_two"] == 0
)
achievement(
    "Body of Steel",
    "Obtain a S rank capure on Registeel",
    id=159692,
    badge="179427",
    points=10,
    trigger=
        save_check() &&
        flicker_check() &&
        prev(pokemon_database["Registeel"]["cptr_one"]) + 
        prev(pokemon_database["Registeel"]["cptr_two"]) != 0 &&
        pokemon_database["Registeel"]["cptr_one"] +
        pokemon_database["Registeel"]["cptr_two"] == 0
)
achievement(
    "Fake God of Pokemon",
    "Obtain a S rank capture on Regigigas",
    id=159591,
    badge="179421",
    points=25,
    trigger=
        save_check() &&
        flicker_check() &&
        prev(pokemon_database["Regigigas"]["cptr_one"]) + 
        prev(pokemon_database["Regigigas"]["cptr_two"]) != 0 &&
        pokemon_database["Regigigas"]["cptr_one"] +
        pokemon_database["Regigigas"]["cptr_two"] == 0
)
achievement(
    "Master of Time",
    "Obtain a S rank capture on Dialga",
    id=159592,
    badge="179422",
    points=10,
    trigger=
        save_check() &&
        flicker_check() &&
        prev(pokemon_database["Dialga"]["cptr_one"]) + 
        prev(pokemon_database["Dialga"]["cptr_two"]) != 0 &&
        pokemon_database["Dialga"]["cptr_one"] +
        pokemon_database["Dialga"]["cptr_two"] == 0
)
achievement(
    "Master of Space",
    "Obtain a S rank capture on Palkia",
    id=159593,
    badge="179423",
    points=10,
    trigger=
        save_check() &&
        flicker_check() &&
        prev(pokemon_database["Palkia"]["cptr_one"]) + 
        prev(pokemon_database["Palkia"]["cptr_two"]) != 0 &&
        pokemon_database["Palkia"]["cptr_one"] +
        pokemon_database["Palkia"]["cptr_two"] == 0
)
achievement(
    "The Time Traveler",
    "Obtain a S rank capture on Celebi",
    id=159693,
    badge="179399",
    points=10,
    trigger=
        save_check() &&
        flicker_check() &&
        prev(pokemon_database["Celebi"]["cptr_one"]) + 
        prev(pokemon_database["Celebi"]["cptr_two"]) != 0 &&
        pokemon_database["Celebi"]["cptr_one"] +
        pokemon_database["Celebi"]["cptr_two"] == 0    
)
achievement(
    "Small Wedding Pokemon",
    "Obtain a S rank capture on Shaymin",
    id=159594,
    badge="179424",
    points=10,
    trigger=
        save_check() &&
        flicker_check() &&
        prev(pokemon_database["Shaymin"]["cptr_one"]) + 
        prev(pokemon_database["Shaymin"]["cptr_two"]) != 0 &&
        pokemon_database["Shaymin"]["cptr_one"] +
        pokemon_database["Shaymin"]["cptr_two"] == 0
)
//=====BROWSER/MISCELLANEOUS=====
function odd_bit_sum(addr) => 
    bit1(addr) + bit3(addr) + bit5(addr) + bit7(addr)
function even_bit_sum(addr) =>
    bit0(addr) + bit2(addr) + bit4(addr) + bit6(addr)
// $0BB250: [NBit=2] Glossary Flags [Field]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1= Friend Pokemon
//          Bit2-3=Partner Pokemon
//          Bit4-5=Partner Energy
//          Bit6-7=Happy Mood
// $0BB251: [NBit=2] Glossary Flags [Field]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Release
//          Bit2-3=Partner Farm
//          Bit4-5=Field Moves and Targets
//          Bit6-7=Target Clear
// $0BB252: [NBit=2] Glossary Flags [Field]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Map Moves
//          Bit2-3=Recharge
//          Bit4-5=Agility
//          Bit6-7=Fly
// $0BB253: [NBit=2] Glossary Flags [Field]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Teleport
//          Bit2-3=Area Moves
//          Bit4-5=Missions
//          Bit6-7=Quests
// $0BB254: [NBit=2] Glossary Flags [Field]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Field Damage
//          Bit2-3=Change Screen Button
function field_new_sum() =>
    even_bit_sum(0x0bb250) +
    even_bit_sum(0x0bb250) +
    even_bit_sum(0x0bb250) +
    even_bit_sum(0x0bb250) +
    bit0(0x0bb254) +
    bit2(0x0bb254)    
function field_read_sum() => //18
    odd_bit_sum(0x0bb250) +
    odd_bit_sum(0x0bb251) +
    odd_bit_sum(0x0bb252) +
    odd_bit_sum(0x0bb253) +
    bit1(0x0bb254) +
    bit3(0x0bb254)
// $0BB260: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Capture Disc
//          Bit2-3=Capture Line
//          Bit4-5=Capture
//          Bit6-7=Capture Results
// $0BB261: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Styler Energy
//          Bit2-3=Styler Damage
//          Bit4-5=Styler Level
//          Bit6-7=Flee
// $0BB262: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Power Charge
//          Bit2-3=Styler Status
//          Bit4-5=Power-up Data
//          Bit6-7=Poke Assists
// $0BB263: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Poke Assist Matchups
//          Bit2-3=Poke Assist Grass
//          Bit4-5=Poke Assist Flying
//          Bit6-7=Poke Assist Normal
// $0BB264: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Poke Assist Recharge
//          Bit2-3=Poke Assist Water
//          Bit4-5=Poke Assist Rock
//          Bit6-7=Poke Assist Electric
// $0BB265: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Poke Assist Bug
//          Bit2-3=Poke Assist Fire
//          Bit4-5=Poke Assist Fighting
//          Bit6-7=Poke Assist Ground
// $0BB266: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Poke Assist Steel
//          Bit2-3=Poke Assist Poison
//          Bit4-5=Poke Assist Ghost
//          Bit6-7=Poke Assist Psychic
// $0BB267: [NBit=2] Glossary Flags [Capture]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Poke Assist Dark
//          Bit2-3=Poke Assist Ice
//          Bit4-5=Poke Assist Dragon
//          Bit6-7=Poke Assist Special Effects
function capture_new_sum() => //32
    even_bit_sum(0x0bb260) +
    even_bit_sum(0x0bb261) +
    even_bit_sum(0x0bb262) +
    even_bit_sum(0x0bb263) +
    even_bit_sum(0x0bb264) +
    even_bit_sum(0x0bb265) +
    even_bit_sum(0x0bb266) +
    even_bit_sum(0x0bb267)        
function capture_read_sum() =>
    odd_bit_sum(0x0bb260) +
    odd_bit_sum(0x0bb261) +
    odd_bit_sum(0x0bb262) +
    odd_bit_sum(0x0bb263) +
    odd_bit_sum(0x0bb264) +
    odd_bit_sum(0x0bb265) +
    odd_bit_sum(0x0bb266) +
    odd_bit_sum(0x0bb267)     
// $0BB270: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Pokemon Rangers
//          Bit2-3=Student Rangers
//          Bit4-5=Top Rangers
//          Bit6-7=Ranger Union
// $0BB271: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Ranger Base
//          Bit2-3=Ranger Depot
//          Bit4-5=Ranger Rank
//          Bit6-7=School Styler
// $0BB272: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Capture Styler
//          Bit2-3=Fine Styler
//          Bit4-5=Vatonage Styler
//          Bit6-7=Ranger Record
// $0BB273: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Capture Arena
//          Bit2-3=Ranger School
//          Bit4-5=Chicole Village
//          Bit6-7=Vientown
// $0BB274: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Vien Forest
//          Bit2-3=Pueltown
//          Bit4-5=Puel Sea
//          Bit6-7=Altru Park
// $0BB275: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Altru Inc.
//          Bit2-3=Peril Cliffs
//          Bit4-5=Boyleland
//          Bit6-7=Boyle Volcano
// $0BB276: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Cargo Ship
//          Bit2-3=Chroma Highlands
//          Bit4-5=Chroma Ruins
//          Bit6-7=Altru Ruins
// $0BB277: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Hia Valley
//          Bit2-3=Shiver Camp
//          Bit4-5=Ice Lake
//          Bit6-7=Almia Castle
// $0BB278: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Sea of Wailord
//          Bit2-3=Oil Field Hideout
//          Bit4-5=Haruba Village
//          Bit6-7=Hippowdon Temple
// $0BB279: [NBit=2] Glossary Flags [Terms]
//          First Bit=New Term
//          Second Bit=Read Term:
//          Bit0-1=Altru Tower
function terms_new_sum() => //37
    even_bit_sum(0xbb270) +
    even_bit_sum(0xbb271) +
    even_bit_sum(0xbb272) +
    even_bit_sum(0xbb273) +
    even_bit_sum(0xbb274) +
    even_bit_sum(0xbb275) +
    even_bit_sum(0xbb276) +
    even_bit_sum(0xbb277) +
    even_bit_sum(0xbb278) +
    bit0(0x0bb279)
function terms_read_sum() =>
    odd_bit_sum(0x0bb270) +
    odd_bit_sum(0x0bb271) +
    odd_bit_sum(0x0bb272) +
    odd_bit_sum(0x0bb273) +
    odd_bit_sum(0x0bb274) +
    odd_bit_sum(0x0bb275) +
    odd_bit_sum(0x0bb276) +
    odd_bit_sum(0x0bb277) +
    odd_bit_sum(0x0bb278) +
    bit1(0x0bb279)
achievement(
    "Draco's Challenge",
    "Read every new terin the Glossary. Knowledge is power!",
    id=159595,
    badge="179428",
    points=5,
    trigger=
        save_check_hits() &&
        prev(
            field_new_sum() + 
            capture_new_sum() + 
            terms_new_sum() 
        ) != 0 &&
        measured(
            field_read_sum() +
            capture_read_sum() +
            terms_read_sum() == 87            
        )        
)
//Gathers suof all bitflags for Browser registering. (Seen & Captured)
function browser_loop(memType){
    trigger = 0    
    if(memType == "delta"){
        for dex_entry in pokemon_database{        
            trigger = trigger + prev(pokemon_database[dex_entry]["dex_two"])            
          }           
          return trigger < 269         
        }
        else{     
        for dex_entry in pokemon_database{
            trigger = trigger + pokemon_database[dex_entry]["dex_two"]                         
          }    
          return measured(trigger == 269)                           
       }                      
}
achievement(
    "The Most Friendly Ranger",
    "Register all 269 capturable Pokemon in the Browser!",
    id=159596,
    badge="179658",
    points=50,
    trigger=
        save_check() &&
        browser_loop("delta") &&
        browser_loop("")
)
//Loops through browser rank data. Repurposed as of 7/2/2021 - Tkt ID: 39878
function capture_loop(mem_type){            
       trigger = []              
       for rank_entry in pokemon_database{
           if(mem_type == "isDelta")          
                array_push(trigger, prev(pokemon_database[rank_entry]["cptr_one"]) == 0 && once(prev(pokemon_database[rank_entry]["cptr_two"]) == 0))           
           else
                array_push(trigger, pokemon_database[rank_entry]["cptr_one"] == 0 && once(pokemon_database[rank_entry]["cptr_two"] == 0))
       }
       return trigger        
    }
achievement(
    "High-Rank Training",
    "Obtain S-Rank captures on at least 25% of the Pokemon in Almia!",
    id=159597,
    badge="179659",
    points=10,
    trigger=        
        save_check_hits() &&
        tally(64, capture_loop("isDelta")) &&
        never(tally(67, capture_loop("isDelta"))) &&
        measured(tally(67, capture_loop("false")))         
)
achievement(
    "Halfway to the Top",
    "Obtain S-Rank captures on at least 50% of the Pokemon in Almia!",
    id=159598,
    badge="179660",
    points=25,
    trigger=
        save_check_hits() &&
        tally(131, capture_loop("isDelta")) &&
        never(tally(134, capture_loop("isDelta"))) &&
        measured(tally(134, capture_loop("false")))         
)
achievement(
   "True Top Ranger",
    "Obtain S-Rank captures on all 269 available Pokemon in Almia!",
   id=159599,
   badge="179661",
   points=50,
   trigger=
        save_check_hits() &&
        tally(266, capture_loop("isDelta")) &&
        never(tally(269, capture_loop("isDelta"))) &&
        measured(tally(269, capture_loop("false"))) 
)
//=====RICH PRESENCE=====
// $0BBB24: [16bit] Party Slot - Partner ID
function party_slot_ID() => word(0x0bbb24)
party_pokemon_ID = {
    0x1f:"[Machop 🥊]",
    0x5c:"[Misdreavus 👻]",
    0x63:"[Sneasel 🌙]",
    0xa1:"[Turtwig 🍁]",
    0xaa:"[Starly 🌪️]",
    0xaf:"[Kricketot 🐞]",
    0xb6:"[Cranidos 💥]",
    0xbc:"[Pachrisu ⚡]",
    0xd2:"[Mime Jr. 🧠]",
    0xd5:"[Gible 🐲]",
    0xd7:"[Munchlax]",
    0xd9:"[Hippopotas 🗿]",
    0xdc:"[Croagunk ☠️]",
    0xe2:"[Snover ❄️]"            
}
// $0BBAFB: Styler Level
function styler_level() => byte(0x0bbafb)
// $08af58: [8bit] Game State
//          0x0=In-Game
//          0x1=In Battle
//          0x3=In Title Screen
//          0x5=In Styler Status Menu
//          0x6=In Options Screen
//          0x7=In Release Menu
//          0x8=In Missions Screen
//          0xb=In Ranger Net
//          0x15=Viewing Browser
//          0x16=Reading Glossary
//          0x1b=In Quests
//          0x1c=Viewing Map

alternative_game_state ={
    0x3:"In Title Screen",
    0xb:"Browsing the Ranger Net",    
    0x5:"In Styler Status Menu",
    0x6:"In Options Menu",
    0x7:"Releasing Pokemon",
    0x8:"In Missions Menu",
    0x16:"Reading Glossary",
    0x1b:"In Quests Menu",
    0x1c:"Viewing Map"
}
area_List = {
    0x0:"Somewhere in Almia",
    0x1:"Ranger School Entrance",
    0x2:"Ranger School Courtyard",
    0x3:"Ranger School Lobby",
    0x4:"Ranger School Lobby for Graduation",
    0x5:"Ranger School Library",
    0x6:"Ascension Square",
    0x7:"Ranger School Offices",
    0x8:"Ms. April's Classroom",
    0x9:"Mr. Kincaid's Classroom",
    0xa:"Ranger School Common Room",
    0xb:"Ranger School Dormitories",
    0xc:"Ranger School Basement",
    0xd:"Kincaid's Lair",
    0xe:"Training Room",
    0xf:"Ascension Square", //Cargo Ship Crash
    0x12:"Ranger School", //Bell Tower - DLC Rescue Riolu
    0x14:"School Road",
    0x15:"School Road",
    0x16:"Vientown",
    0x17:"Vientown Ranger Station",
    0x19:"Vientown Milktank Farm",
    0x1a:"Mimi's House",
    0x1b:"Mr. Woodward's House",
    0x1c:"Breeze Hill near Vientown",
    0x1d:"Vientown",
    0x1e:"Vientown Ranger Station",
    0x1f:"Vientown Milktank Farm",
    0x20:"Mimi's House",
    0x21:"Mr. Woodward's House",
    0x22:"Breeze Hill near Vientown",
    0x23:"Nabiki Beach",
    0x24:"Nabiki Beach", //Mission 3 only?
    0x25:"Nabiki Beach", //DLC - Manaphy Egg
    0x26:"Nabiki Beach",
    0x27:"Nabiki Beach", //DLC - Palkia
    0x28:"Marine Cave", //Mission 3 only?
    0x29:"Marine Cave", //Mission 3 only?
    0x2a:"Marine Cave",
    0x2b:"Marine Cave",
    0x2c:"Chicole Path",
    0x2d:"Chicole Village",
    0x2e:"Their Home",
    0x2f:"Their Home", //Player House
    0x30:"Paul & Paula's House",
    0x31:"Ollie's House",
    0x32:"The Partner Farm",
    0x33:"Kyle's House",
    0x34:"Path West of the Partner Farm",
    0x35:"Their Home", //Dialga DLC
    0x36:"Vientown",
    0x37:"Their Home", //Dialga DLC
    0x38:"Vien Forest", //Burning or not?
    0x39:"Vien Forest",
    0x3b:"Vien Forest",
    0x40:"Vien Forest",
    0x41:"Vien Forest",
    0x42:"Vien Forest",
    0x43:"Vien Forest",
    0x44:"Vien Forest",
    0x48:"Altru Building",
    0x49:"Pueltown",
    0x4a:"Pueltown",
    0x4b:"Pueltown Harbor",
    0x4c:"Pueltown Ranger Depot",
    0x4d:"Pueltown", //Old Lady's House in Pueltown Right
    0x52:"Pueltown", //Old Lady's House in Pueltown Left
    0x5a:"Sailors' Inn",
    0x5b:"Pueltown",
    0x5c:"Pueltown",
    0x5d:"Pueltown",
    0x5e:"Pueltown",
    0x5f:"Puel Sea",
    0x60:"Puel Sea",
    0x61:"Puel Sea",
    0x62:"Puel Sea",
    0x63:"Puel Sea",
    0x64:"Altru Park",
    0x65:"Outside Altru Inc.",
    0x66:"Altru Park",
    0x67:"Norward Bridge",
    0x68:"Altru Park",
    0x6a:"Altru Park",
    0x6c:"Altru Park",
    0x6d:"Union Road",
    0x6f:"Union Road",
    0x70:"Union Road",
    0x71:"Union Road River",
    0x72:"Union Road",
    0x73:"Peril Cliffs",
    0x74:"Peril Cliffs", //w/Gigaremo?
    0x75:"Peril Cliffs",
    0x76:"Peril Cliffs",
    0x77:"Outside of Ranger Union",
    0x78:"Ranger Union",
    0x79:"Ranger Union",
    0x7a:"Ranger Union",
    0x7b:"Ranger Union",
    0x7c:"Ranger Union",
    0x7d:"Ranger Union",
    0x7e:"Ranger Union",
    0x7f:"Ranger Union Roof",
    0x80:"Ranger Union",
    0x83:"Ranger Union",
    0x84:"Ranger Union",
    0x85:"Ranger Union",
    0x86:"Boyleland",
    0x87:"Boyleland",
    0x88:"Boyleland",
    0x89:"Boyleland",
    0x8a:"Boyleland",
    0x8b:"Boyleland",
    0x8c:"Volcano Cave",
    0x8d:"Volcano Cave",
    0x8e:"Volcano Cave",
    0x8f:"Volcano Cave",
    0x90:"Volcano Cave",
    0x91:"Volcano Cave",
    0x92:"Volcano Cave", //Final Cutscene
    0x93:"Volcano Cave", //DLC - Palkia
    0x94:"Volcano Cave",
    0x95:"Volcano Cave",
    0x96:"Volcano Cave",
    0x97:"Volcano Cave",
    0x98:"Volcano Cave",
    0x99:"Volcano Cave",
    0x9a:"Volcano Cave",
    0x9c:"Volcano Cave",
    0x9e:"Cargo Ship",
    0x9f:"Cargo Ship",
    0xa0:"Cargo Ship",
    0xa1:"Cargo Ship",
    0xa2:"Cargo Ship",
    0xa3:"Cargo Ship",
    0xa4:"Cargo Ship",
    0xa5:"Cargo Ship",
    0xa6:"Cargo Ship",
    0xa7:"Cargo Ship",
    0xa8:"Cargo Ship",
    0xaa:"Cargo Ship",
    0xab:"Cargo Ship",
    0xac:"Cargo Ship",
    0xad:"Cargo Ship",
    0xae:"Chroma Road",
    0xaf:"Chroma Road",
    0xb0:"Chroma Road",
    0xb1:"Chroma Highlands",
    0xb2:"Chroma Highlands",
    0xb3:"Chroma Highlands",
    0xb4:"Chroma Highlands",
    0xb5:"Chroma Ruins",
    0xb6:"Chroma Ruins",
    0xb7:"Chroma Ruins",
    0xb8:"Chroma Ruins",
    0xb9:"Chroma Ruins",
    0xba:"Chroma Ruins",
    0xbb:"Chroma Ruins",
    0xbc:"Chroma Ruins",
    0xbd:"Chroma Ruins",
    0xbf:"Chroma Ruins",
    0xc1:"Chroma Ruins",
    0xc2:"Chroma Ruins",
    0xc3:"Chroma Ruins",
    0xc4:"Chroma Ruins",
    0xc5:"Chroma Ruins",
    0xc6:"Choma Ruins",
    0xc7:"Chroma Ruins", //DLC - Palkia
    0xc8:"Crysta Cave",
    0xc9:"Crysta Cave",
    0xcb:"Crysta Cave",
    0xcc:"Crysta Cave",
    0xce:"Crysta Cave",
    0xcf:"Shiver Camp",
    0xd0:"Shiver Camp",
    0xd1:"Shiver Camp",
    0xd2:"Shiver Camp Ranger Station",
    0xd3:"Shiver Camp",
    0xd4:"Shiver Camp Ranger Station",
    0xd5:"Hia Valley",
    0xd6:"Mrs. Winter's Cabin",
    0xd7:"Ice Lake",
    0xd8:"Ice Lake",
    0xd9:"Ice Lake",
    0xda:"Ice Lake",
    0xdb:"Ice Lake", //Dialga DLC
    0xdc:"Almia Castle",
    0xde:"Almia Castle",
    0xdf:"Almia Castle",
    0xe0:"Almia Castle",
    0xe1:"Almia Castle",
    0xe2:"Almia Castle",
    0xe3:"Almia Castle",
    0xe4:"Almia Castle",
    0xe5:"Almia Castle",
    0xe6:"Almia Castle",
    0xe7:"Almia Castle",
    0xe8:"Almia Castle",
    0xe9:"Almia Castle",
    0xea:"Almia Castle",
    0xec:"Almia Castle",
    0xed:"Almia Castle",
    0xee:"Almia Castle",
    0xef:"Almia Castle",
    0xf0:"Almia Castle",
    0xf1:"Almia Castle",
    0xf2:"Almia Castle", //After Blue Barrier is Broken
    0xf3:"Almia Castle",
    0xf4:"Almia Castle",
    0xf5:"Almia Castle",
    0xf6:"Almia Castle",
    0xf7:"Almia Castle",
    0xf9:"Almia Castle",
    0xfb:"Almia Castle",
    0xfc:"Almia Castle",
    0xfd:"Almia Castle",
    0xfe:"Almia Castle",
    0xff:"Almia Castle",
    0x100:"Sea of Wailord",
    0x101:"Sea of Wailord",
    0x102:"Sea of Wailord",
    0x105:"Sea of Wailord",
    0x108:"Sea of Wailord",
    0x10a:"Oil Field Hideout",
    0x10b:"Oil Field Hideout",
    0x10c:"Oil Field Hideout",
    0x10d:"Oil Field Hideout",
    0x10e:"Oil Field Hideout",
    0x10f:"Oil Field Hideout",
    0x110:"Oil Field Hideout",
    0x111:"Oil Field Hideout",
    0x112:"Oil Field Hideout",
    0x113:"Oil Field Hideout",
    0x114:"Oil Field Hideout",
    0x115:"Oil Field Hideout",
    0x116:"Oil Field Hideout",
    0x117:"Oil Field Hideout",
    0x118:"Oil Field Hideout",
    0x119:"Oil Field Hideout",
    0x11a:"Oil Field Hideout",
    0x11b:"Oil Field Hideout",
    0x11c:"Oil Field Hideout",
    0x11d:"Oil Field Hideout",
    0x11e:"Oil Field Hideout",
    0x11f:"Kincaid's Oil Field HQ",
    0x120:"Oil Field Hideout",
    0x121:"Oil Field Hideout",
    0x122:"Oil Field Hideout",
    0x123:"Oil Field Hideout",
    0x124:"Oil Field Hideout",
    0x125:"Oil Field Hideout",
    0x126:"Haruba Village",
    0x127:"Haruba Village",
    0x129:"Haruba Village",
    0x12a:"Haruba Village",
    0x12b:"Haruba Village",
    0x12c:"Haruba Village",
    0x12d:"Haruba Village",
    0x12f:"Haruba Desert",
    0x130:"Haruba Desert",
    0x131:"Hippowdon Temple",
    0x132:"Hippowdon Temple", //NO DAMAGE CHALLENGE
    0x133:"Hippowdon Temple",
    0x134:"Hippowdon Temple",
    0x135:"Hippowdon Temple",
    0x136:"Hippowdon Temple",
    0x137:"Hippowdon Temple",
    0x138:"Hippwdown Temple",
    0x139:"Hippowdon Temple",
    0x13a:"Hippowdon Temple",
    0x13b:"Hippowdon Temple",
    0x13c:"Hippowdon Temple",
    0x13d:"Hippowdon Temple",
    0x13e:"Hippowdon Temple",
    0x13f:"Hippowdon Temple",
    0x140:"Hippowdon Temple",
    0x143:"Hippowdon Temple",
    0x144:"Hippowdon Temple",
    0x145:"Hippowdon Temple",
    0x146:"Hippowdon Temple",
    0x147:"Hippowdon Temple", //DLC - Palkia Chamber
    0x148:"Altru Building",
    0x149:"Altru Building",
    0x14a:"Altru Building",
    0x14b:"Altru Building",
    0x14c:"Altru Building",
    0x14d:"Altru Building",
    0x14e:"Altru Building",
    0x14f:"Altru Building",
    0x150:"Altru Building",
    0x151:"Altru Building",
    0x152:"Altru Building",
    0x153:"Altru Building",
    0x154:"Altru Building",
    0x155:"Altru Building",
    0x156:"Altru Building",
    0x157:"Altru Building",
    0x158:"Altru Building",
    0x159:"Altru Building",
    0x15a:"Altru Building",
    0x15b:"Altru Building",    
    0x15c:"Altru Tower",
    0x15d:"Altru Tower",
    0x15e:"Altru Tower",
    0x15f:"Altru Tower",
    0x160:"Altru Tower", //Rhyperior Boss room
    0x161:"Altru Tower",
    0x162:"Altru Tower",
    0x163:"Altru Tower",
    0x164:"Altru Tower",
    0x165:"Altru Tower", //Barrier 2 destroyed?
    0x166:"Altru Tower",
    0x167:"Altru Tower", //Transition Roobefore 3rd Barrier Destroyed.
    0x168:"Altru Tower", //Ice
    0x169:"Altru Tower", //3rd Barrier (Destroyed)
    0x16a:"Altru Tower",
    0x16b:"Top of Altru Tower",
    0x16c:"Altru Tower",
    0x16e:"Altru Tower",
    0x16f:"Altru Tower",
    0x170:"Altru Tower",
    0x171:"Altru Tower",
    0x173:"Altru Tower",
    0x174:"Altru Tower",
    0x175:"Altru Tower",
    0x176:"Altru Tower",
    0x177:"Altru Tower",
    0x178:"Altru Tower",
    0x179:"Altru Tower",
    0x17a:"Altru Tower",
    0x17b:"Altru Tower",
    0x17c:"Altru Tower",
    0x17d:"Altru Tower",
    0x17e:"Top of Altru Tower",
    0x17f:"Capture Arena",
    0x180:"Capture Arena",
    0x181:"Capture Arena",
    0x182:"Capture Arena 1F",
    0x183:"Capture Arena 1F",
    0x184:"Capture Arena 1F",
    0x185:"Capture Arena 1F",
    0x186:"Capture Arena 1F",
    0x187:"Capture Arena 1F",
    0x188:"Capture Arena 1F",
    0x189:"Capture Arena 1F",
    0x18a:"Capture Arena 1F",
    0x18b:"Capture Arena 1F",
    0x18c:"Capture Arena 1F",
    0x18d:"Capture Arena 1F",
    0x18e:"Capture Arena 1F",
    0x18f:"Capture Arena 1F",
    0x190:"Capture Arena 1F",
    0x191:"Capture Arena 1F",
    0x192:"Capture Arena 1F", //Cresselia's Room
    0x193:"Capture Arena 1F",
    0x194:"Capture Arena 1F",
    0x195:"Capture Arena 1F",
    0x196:"Capture Arena 2F",
    0x197:"Capture Arena 2F",
    0x198:"Capture Arena 2F",
    0x199:"Capture Arena 2F",
    0x19a:"Capture Arena 2F",
    0x19b:"Capture Arena 2F",
    0x19c:"Capture Arena 2F",
    0x19d:"Capture Arena 2F",
    0x19e:"Capture Arena 2F",
    0x19f:"Capture Arena 2F",
    0x1a0:"Capture Arena 2F",
    0x1a1:"Capture Arena 2F",
    0x1a2:"Capture Arena 2F",
    0x1a3:"Capture Arena 2F",
    0x1a4:"Capture Arena 2F",
    0x1a5:"Capture Arena 2F",
    0x1a6:"Capture Arena 2F",
    0x1a7:"Capture Arena 2F",
    0x1a8:"Capture Arena 2F",
    0x1a9:"Capture Arena 2F",
    0x1aa:"Capture Arena 2F",
    0x1ab:"Capture Arena 2F",
    0x1ac:"Capture Arena 2F",
    0x1ad:"Capture Arena 2F",
    0x1ae:"Capture Arena 2F",
    0x1af:"Capture Arena 2F",
    0x1b0:"Capture Arena 2F",
    0x1b1:"Capture Arena 3F",
    0x1b3:"Capture Arena 3F",
    0x1b5:"Ocean Route",
    0x1b6:"Ocean Route"
}
function browser_caught_sum() {
    count = 0 
    for pkmn_rp in pokemon_database
        count = count + pokemon_database[pkmn_rp]["dex_two"]
    return count
}
rich_presence_conditional_display(game_state() == 0x15, "Viewing Browser 🎱 {0}/270",
rich_presence_value("Caught", browser_caught_sum() 
    )
)
rich_presence_conditional_display(game_state() == 0x1, "Befriending a Pokemon! Styler Level {0} {1}",
rich_presence_value("Level", styler_level()), 
rich_presence_lookup("Partner", party_slot_ID(), party_pokemon_ID)
)
rich_presence_conditional_display(game_state() == 0x0, "On patrol in {0}",
rich_presence_lookup("Area", location(), area_List)
)
rich_presence_display("{0}",
rich_presence_lookup("AltGameState", game_state(), alternative_game_state)) //Other Menus.
//=====LEADERBOARDS=====
//RooID:
//0x101=BottoEntrance
//0x102=Top Entrance
//0x105=Qwilfish Room
leaderboard(
    "Qwilfish Speedrun",
    "Fastest time to get through Qwilfish rooin Sea of Wailord",
    prev(location()) == 0x101 && location() == 0x105,
    prev(location()) == 0x105 && location() == 0x101,
    prev(location()) == 0x105 && location() == 0x102,
    always_true(),
    "FRAMES"    
)
